// Batch 3 of problems

export const p21 = {
        id: 'p21',
        title: 'Product of Array Except Self',
        problemStatement: 'Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].\n\nThe product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.\n\nYou must solve it without using division and in O(n) time.',
        inputFormat: 'First line: n. Second line: n space-separated integers.',
        outputFormat: 'Print the result array as space-separated integers.',
        sampleInput: '4\n1 2 3 4',
        sampleOutput: '24 12 8 6',
        difficulty: 'Medium',
        category: 'Arrays',
        constraints: '2 <= n <= 10^5\n-30 <= nums[i] <= 30\nProduct of any prefix or suffix fits in a 32-bit integer.',
        companies: ['Amazon', 'Meta', 'Apple', 'Microsoft'],
        order: 21,
        starterCodes: { python3: '// Compute product of array except self without division\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0: print("true")\nelse:\n    nodes = input().split()\n    print("true" if nodes == nodes[::-1] else "false")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['4', '1 2 3 4'], output: ['24 12 8 6'] },
            { input: ['5', '-1 1 0 -3 3'], output: ['0 0 9 0 0'] },
            { input: ['2', '1 2'], output: ['2 1'] },
            { input: ['3', '1 2 3'], output: ['6 3 2'] },
            { input: ['4', '1 1 1 1'], output: ['1 1 1 1'] },
            { input: ['3', '0 0 0'], output: ['0 0 0'] },
            { input: ['3', '1 0 3'], output: ['0 3 0'] },
            { input: ['3', '0 4 5'], output: ['20 0 0'] },
            { input: ['2', '10 10'], output: ['10 10'] },
            { input: ['5', '2 3 4 5 6'], output: ['360 240 180 144 120'] },
            { input: ['4', '-1 -2 -3 -4'], output: ['-24 -12 -8 -6'] },
            { input: ['3', '1 -1 1'], output: ['-1 1 -1'] },
            { input: ['4', '1 2 0 0'], output: ['0 0 0 0'] },
            { input: ['2', '0 0'], output: ['0 0'] },
            { input: ['5', '1 2 3 0 5'], output: ['0 0 0 30 0'] }
        ],
        videoId: 'bNvIQI2wAjk'
    };

export const p22 = {
        id: 'p22',
        title: 'Valid Anagram',
        problemStatement: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise.\n\nAn Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.',
        inputFormat: 'First line: string s. Second line: string t.',
        outputFormat: 'Print "true" if t is an anagram of s, "false" otherwise.',
        sampleInput: 'anagram\nnagaram',
        sampleOutput: 'true',
        difficulty: 'Easy',
        category: 'Strings',
        constraints: '1 <= s.length, t.length <= 5 * 10^4\ns and t consist of lowercase English letters.',
        companies: ['Amazon', 'Bloomberg', 'Google'],
        order: 22,
        starterCodes: { python3: '// Check if two strings are anagrams\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nnums.sort()\nl, r = 0, len(nums) - 1\nres = []\nwhile l <= r:\n    if l == r: res.append(nums[l])\n    else:\n        res.append(nums[r])\n        res.append(nums[l])\n    l += 1; r -= 1\nprint(" ".join(map(str, res)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['anagram', 'nagaram'], output: ['true'] },
            { input: ['rat', 'car'], output: ['false'] },
            { input: ['a', 'a'], output: ['true'] },
            { input: ['ab', 'ba'], output: ['true'] },
            { input: ['ab', 'ac'], output: ['false'] },
            { input: ['a', 'b'], output: ['false'] },
            { input: ['abc', 'cba'], output: ['true'] },
            { input: ['hello', 'olleh'], output: ['true'] },
            { input: ['world', 'dlrow'], output: ['true'] },
            { input: ['anagrams', 'nagaram'], output: ['false'] },
            { input: ['aacc', 'ccac'], output: ['false'] },
            { input: ['race', 'care'], output: ['true'] },
            { input: ['aa', 'bb'], output: ['false'] },
            { input: ['listen', 'silent'], output: ['true'] },
            { input: ['apple', 'pale'], output: ['false'] }
        ],
        videoId: '9UtInBqnCgA'
    };

export const p23 = {
        id: 'p23',
        title: 'Longest Substring Without Repeating Characters',
        problemStatement: 'Given a string s, find the length of the longest substring without repeating characters.\n\nA substring is a contiguous non-empty sequence of characters within a string.',
        inputFormat: 'A single line containing the string s.',
        outputFormat: 'Print the length of the longest substring without repeating characters.',
        sampleInput: 'abcabcbb',
        sampleOutput: '3',
        difficulty: 'Medium',
        category: 'Sliding Window',
        constraints: '0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.',
        companies: ['Amazon', 'Google', 'Meta', 'Bloomberg', 'Apple'],
        order: 23,
        starterCodes: { python3: '// Find the longest substring without repeating characters\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nprint(" ".join(map(str, sorted(list(set(nums))))))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['abcabcbb'], output: ['3'] },
            { input: ['bbbbb'], output: ['1'] },
            { input: ['pwwkew'], output: ['3'] },
            { input: [''], output: ['0'] },
            { input: ['abcdef'], output: ['6'] },
            { input: ['dvdf'], output: ['3'] },
            { input: ['anviaj'], output: ['5'] },
            { input: ['tmmzuxt'], output: ['5'] },
            { input: ['abacadae'], output: ['2'] },
            { input: ['1231234'], output: ['4'] },
            { input: ['!@#$%^&*'], output: ['8'] },
            { input: ['a ab'], output: ['3'] },
            { input: ['aab'], output: ['2'] },
            { input: ['abb'], output: ['2'] },
            { input: ['abba'], output: ['2'] }
        ],
        videoId: 'wiGpQwVHdE0'
    };

export const p24 = {
        id: 'p24',
        title: 'Minimum Window Substring',
        problemStatement: 'Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window.\n\nIf there is no such substring, return an empty string "".\n\nThe answer is guaranteed to be unique.',
        inputFormat: 'First line: string s. Second line: string t.',
        outputFormat: 'Print the minimum window substring, or "" if none exists.',
        sampleInput: 'ADOBECODEBANC\nABC',
        sampleOutput: 'BANC',
        difficulty: 'Hard',
        category: 'Sliding Window',
        constraints: 'm == s.length\nn == t.length\n1 <= m, n <= 10^5\ns and t consist of uppercase and lowercase English letters.',
        companies: ['Meta', 'Amazon', 'Google', 'Airbnb', 'Uber'],
        order: 24,
        starterCodes: { python3: '// Find the minimum window substring containing all characters of t\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nif not nums: print(0)\nelse:\n    res = nums[0]\n    curMin, curMax = 1, 1\n    for n in nums:\n        tmp = curMax * n\n        curMax = max(n * curMax, n * curMin, n)\n        curMin = min(tmp, n * curMin, n)\n        res = max(res, curMax)\n    print(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['ADOBECODEBANC', 'ABC'], output: ['BANC'] },
            { input: ['a', 'a'], output: ['a'] },
            { input: ['a', 'aa'], output: [''] },
            { input: ['a', 'b'], output: [''] },
            { input: ['aa', 'a'], output: ['a'] },
            { input: ['ab', 'a'], output: ['a'] },
            { input: ['ab', 'b'], output: ['b'] },
            { input: ['abc', 'bc'], output: ['bc'] },
            { input: ['bdab', 'ab'], output: ['ab'] },
            { input: ['ADOBECODEBANC', 'ABCC'], output: ['CODEBANC'] },
            { input: ['A', 'A'], output: ['A'] },
            { input: ['AA', 'AA'], output: ['AA'] },
            { input: ['ABC', 'D'], output: [''] },
            { input: ['XYZ', 'XZ'], output: ['XYZ'] },
            { input: ['ABCA', 'AA'], output: ['ABCA'] }
        ],
        videoId: 'jSto0O4AJbM'
    };

export const p25 = {
        id: 'p25',
        title: 'Binary Tree Level Order Traversal',
        problemStatement: 'Given the root of a binary tree in level-order format (with -1 for null), return the level order traversal of its nodes\' values (i.e., from left to right, level by level).\n\nPrint each level on a separate line.',
        inputFormat: 'First line: n (number of elements). Second line: n space-separated integers (-1 for null).',
        outputFormat: 'Print each level\'s values on a separate line, space-separated.',
        sampleInput: '7\n3 9 20 -1 -1 15 7',
        sampleOutput: '3\n9 20\n15 7',
        difficulty: 'Medium',
        category: 'Trees',
        constraints: 'The number of nodes is in [0, 2000].\n-1000 <= Node.val <= 1000',
        companies: ['Amazon', 'Meta', 'Microsoft', 'Bloomberg'],
        order: 25,
        starterCodes: { python3: '// Perform level-order traversal of a binary tree\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'rows = int(input())\ngrid = [list(map(int, input().split())) for _ in range(rows)]\nif not grid: print(0)\nelse:\n    m, n = len(grid), len(grid[0])\n    dp = [[0] * n for _ in range(m)]\n    dp[0][0] = grid[0][0]\n    for i in range(1, m): dp[i][0] = dp[i-1][0] + grid[i][0]\n    for j in range(1, n): dp[0][j] = dp[0][j-1] + grid[0][j]\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[i][j] = min(dp[i-1][j], dp[i][j-1]) + grid[i][j]\n    print(dp[-1][-1])', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['7', '3 9 20 -1 -1 15 7'], output: ['3', '9 20', '15 7'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['0', ''], output: [''] },
            { input: ['3', '1 2 3'], output: ['1', '2 3'] },
            { input: ['2', '1 2'], output: ['1', '2'] },
            { input: ['3', '1 -1 2'], output: ['1', '2'] },
            { input: ['3', '1 2 -1'], output: ['1', '2'] },
            { input: ['7', '1 2 3 4 5 6 7'], output: ['1', '2 3', '4 5 6 7'] },
            { input: ['3', '1 2 2'], output: ['1', '2 2'] },
            { input: ['15', '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15'], output: ['1', '2 3', '4 5 6 7', '8 9 10 11 12 13 14 15'] },
            { input: ['4', '1 2 3 4'], output: ['1', '2 3', '4'] },
            { input: ['6', '1 2 3 -1 4 5'], output: ['1', '2 3', '4 5'] },
            { input: ['7', '1 -1 2 -1 3 -1 4'], output: ['1', '2', '3', '4'] },
            { input: ['5', '1 2 3 4 -1'], output: ['1', '2 3', '4'] },
            { input: ['2', '1 -1'], output: ['1'] }
        ],
        videoId: '6ZnyEApgFYg'
    };

export const p26 = {
        id: 'p26',
        title: 'Topological Sort',
        problemStatement: 'Given a directed acyclic graph (DAG) with V vertices and E edges, find a topological ordering of the vertices.\n\nA topological ordering is a linear ordering of vertices such that for every directed edge u → v, vertex u comes before v in the ordering.\n\nIf multiple valid orderings exist, print any one of them.',
        inputFormat: 'First line: V E (number of vertices and edges). Next E lines each contain: u v (directed edge from u to v). Vertices are 0-indexed.',
        outputFormat: 'Print the topological order as space-separated vertex indices.',
        sampleInput: '6 6\n5 2\n5 0\n4 0\n4 1\n2 3\n3 1',
        sampleOutput: '5 4 2 3 1 0',
        difficulty: 'Medium',
        category: 'Graphs',
        constraints: '2 <= V <= 1000\n1 <= E <= V*(V-1)/2\nThe graph is a DAG.',
        companies: ['Amazon', 'Google', 'Microsoft', 'Intuit'],
        order: 26,
        starterCodes: { python3: '// Perform topological sort on a directed acyclic graph\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nnums.sort()\nres = []\nfor i, a in enumerate(nums):\n    if i > 0 and a == nums[i-1]: continue\n    l, r = i + 1, len(nums) - 1\n    while l < r:\n        threeSum = a + nums[l] + nums[r]\n        if threeSum > 0: r -= 1\n        elif threeSum < 0: l += 1\n        else:\n            res.append([a, nums[l], nums[r]])\n            l += 1\n            while nums[l] == nums[l-1] and l < r: l += 1\nfor r in sorted(res): print(" ".join(map(str, r)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6 6', '5 2', '5 0', '4 0', '4 1', '2 3', '3 1'], output: ['5 4 2 3 1 0'] },
            { input: ['4 3', '0 1', '0 2', '2 3'], output: ['0 2 3 1'] },
            { input: ['2 1', '0 1'], output: ['0 1'] },
            { input: ['3 2', '0 1', '1 2'], output: ['0 1 2'] },
            { input: ['3 3', '0 1', '0 2', '1 2'], output: ['0 1 2'] },
            { input: ['1 0'], output: ['0'] },
            { input: ['2 0'], output: ['0 1'] },
            { input: ['5 4', '0 1', '1 2', '2 3', '3 4'], output: ['0 1 2 3 4'] },
            { input: ['5 0'], output: ['0 1 2 3 4'] },
            { input: ['4 4', '0 1', '2 3', '0 2', '1 3'], output: ['0 1 2 3'] },
            { input: ['3 2', '2 1', '1 0'], output: ['2 1 0'] },
            { input: ['4 2', '1 2', '3 0'], output: ['1 3 2 0'] },
            { input: ['3 1', '1 2'], output: ['0 1 2'] },
            { input: ['2 1', '1 0'], output: ['1 0'] },
            { input: ['6 5', '5 4', '4 3', '3 2', '2 1', '1 0'], output: ['5 4 3 2 1 0'] }
        ],
        videoId: 'dis_c84ejhQ'
    };

export const p27 = {
        id: 'p27',
        title: 'N-Queens',
        problemStatement: 'The N-Queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.\n\nGiven an integer n, return the number of distinct solutions to the N-Queens puzzle.\n\nA queen can attack horizontally, vertically, and diagonally.',
        inputFormat: 'A single integer n.',
        outputFormat: 'Print the number of distinct solutions.',
        sampleInput: '4',
        sampleOutput: '2',
        difficulty: 'Hard',
        category: 'Backtracking',
        constraints: '1 <= n <= 9',
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
        order: 27,
        starterCodes: { python3: '// Count the number of solutions to the N-Queens problem\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\ncol = set()\nposDiag = set()\nnegDiag = set()\nres = 0\ndef backtrack(r):\n    if r == n:\n        nonlocal res\n        res += 1\n        return\n    for c in range(n):\n        if c in col or (r + c) in posDiag or (r - c) in negDiag:\n            continue\n        col.add(c)\n        posDiag.add(r + c)\n        negDiag.add(r - c)\n        backtrack(r + 1)\n        col.remove(c)\n        posDiag.remove(r + c)\n        negDiag.remove(r - c)\nbacktrack(0)\nprint(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['1'], output: ['1'] },
            { input: ['4'], output: ['2'] },
            { input: ['8'], output: ['92'] },
            { input: ['2'], output: ['0'] },
            { input: ['3'], output: ['0'] },
            { input: ['5'], output: ['10'] },
            { input: ['6'], output: ['4'] },
            { input: ['7'], output: ['40'] },
            { input: ['9'], output: ['352'] },
            { input: ['4'], output: ['2'] },
            { input: ['1'], output: ['1'] },
            { input: ['2'], output: ['0'] },
            { input: ['3'], output: ['0'] },
            { input: ['5'], output: ['10'] },
            { input: ['6'], output: ['4'] }
        ],
        videoId: 'Ph95IHmRp5M'
    };

export const p28 = {
        id: 'p28',
        title: 'Kth Largest Element in Array',
        problemStatement: 'Given an integer array nums and an integer k, return the kth largest element in the array.\n\nNote that it is the kth largest element in the sorted order, not the kth distinct element.\n\nCan you solve it without sorting?',
        inputFormat: 'First line: n k. Second line: n space-separated integers.',
        outputFormat: 'Print the kth largest element.',
        sampleInput: '6 2\n3 2 1 5 6 4',
        sampleOutput: '5',
        difficulty: 'Medium',
        category: 'Heap',
        constraints: '1 <= k <= n <= 10^5\n-10^4 <= nums[i] <= 10^4',
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
        order: 28,
        starterCodes: { python3: '// Find the kth largest element in an unsorted array\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n, k = map(int, input().split())\nnums = list(map(int, input().split()))\nnums.sort()\nprint(nums[-k])', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6 2', '3 2 1 5 6 4'], output: ['5'] },
            { input: ['9 4', '3 2 3 1 2 4 5 5 6'], output: ['4'] },
            { input: ['1 1', '42'], output: ['42'] },
            { input: ['2 1', '1 2'], output: ['2'] },
            { input: ['2 2', '1 2'], output: ['1'] },
            { input: ['5 1', '1 2 3 4 5'], output: ['5'] },
            { input: ['5 5', '1 2 3 4 5'], output: ['1'] },
            { input: ['3 2', '1 1 1'], output: ['1'] },
            { input: ['4 3', '10 20 30 40'], output: ['20'] },
            { input: ['5 2', '5 5 5 5 5'], output: ['5'] },
            { input: ['6 3', '1 5 2 4 3 6'], output: ['4'] },
            { input: ['3 1', '-1 -2 -3'], output: ['-1'] },
            { input: ['3 3', '-1 -2 -3'], output: ['-3'] },
            { input: ['5 3', '0 0 0 0 0'], output: ['0'] },
            { input: ['10 1', '1 2 3 4 5 6 7 8 9 10'], output: ['10'] }
        ],
        videoId: 'XEmy13g1Qc8'
    };

export const p29 = {
        id: 'p29',
        title: 'Word Search in Grid',
        problemStatement: 'Given an m x n grid of characters board and a string word, return true if word exists in the grid.\n\nThe word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.',
        inputFormat: 'First line: m n (rows and cols). Next m lines: n space-separated characters. Last line: the word to search.',
        outputFormat: 'Print "true" if word exists, "false" otherwise.',
        sampleInput: '3 4\nA B C E\nS F C S\nA D E E\nABCCED',
        sampleOutput: 'true',
        difficulty: 'Medium',
        category: 'Backtracking',
        constraints: 'm == board.length\nn == board[i].length\n1 <= m, n <= 6\n1 <= word.length <= 15\nboard and word consist of only lowercase and uppercase English letters.',
        companies: ['Amazon', 'Microsoft', 'Bloomberg', 'Snapchat'],
        order: 29,
        starterCodes: { python3: '// Search for a word in a 2D grid using backtracking\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'm, n = map(int, input().split())\nboard = [input().split() for _ in range(m)]\nword = input().strip()\npath = set()\ndef dfs(r, c, i):\n    if i == len(word): return True\n    if (r < 0 or c < 0 or r >= m or c >= n or word[i] != board[r][c] or (r, c) in path):\n        return False\n    path.add((r, c))\n    res = (dfs(r + 1, c, i + 1) or dfs(r - 1, c, i + 1) or dfs(r, c + 1, i + 1) or dfs(r, c - 1, i + 1))\n    path.remove((r, c))\n    return res\nfound = False\nfor r in range(m):\n    for c in range(n):\n        if dfs(r, c, 0):\n            found = True\n            break\n    if found: break\nprint("true" if found else "false")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3 4', 'A B C E', 'S F C S', 'A D E E', 'ABCCED'], output: ['true'] },
            { input: ['3 4', 'A B C E', 'S F C S', 'A D E E', 'SEE'], output: ['true'] },
            { input: ['3 4', 'A B C E', 'S F C S', 'A D E E', 'ABCB'], output: ['false'] },
            { input: ['1 1', 'A', 'A'], output: ['true'] },
            { input: ['1 1', 'A', 'B'], output: ['false'] },
            { input: ['2 2', 'A B', 'C D', 'ABCD'], output: ['false'] },
            { input: ['2 2', 'A B', 'C D', 'ACDB'], output: ['true'] },
            { input: ['1 2', 'A B', 'BA'], output: ['true'] },
            { input: ['2 1', 'A', 'B', 'AB'], output: ['true'] },
            { input: ['3 3', 'A B C', 'D E F', 'G H I', 'AEI'], output: ['false'] },
            { input: ['3 3', 'A B C', 'D E F', 'G H I', 'ADG'], output: ['true'] },
            { input: ['2 2', 'A A', 'A A', 'AAAA'], output: ['true'] },
            { input: ['2 2', 'A A', 'A A', 'AAAAA'], output: ['false'] },
            { input: ['3 4', 'A B C E', 'S F C S', 'A D E E', 'ABCESEEEFS'], output: ['true'] },
            { input: ['1 3', 'A B C', 'ACB'], output: ['false'] }
        ],
        videoId: 'pfiQ_PS1g8E'
    };

export const p30 = {
        id: 'p30',
        title: 'Longest Palindromic Substring',
        problemStatement: 'Given a string s, return the longest palindromic substring in s.\n\nA palindrome is a string that reads the same forward and backward.',
        inputFormat: 'A single line containing the string s.',
        outputFormat: 'Print the longest palindromic substring. If multiple answers exist, print any one.',
        sampleInput: 'babad',
        sampleOutput: 'bab',
        difficulty: 'Medium',
        category: 'Strings',
        constraints: '1 <= s.length <= 1000\ns consist of only digits and English letters.',
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
        order: 30,
        starterCodes: { python3: '// Find the longest palindromic substring\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 's = input().strip()\nres = ""\nresLen = 0\nfor i in range(len(s)):\n    l, r = i, i\n    while l >= 0 and r < len(s) and s[l] == s[r]:\n        if (r - l + 1) > resLen:\n            res = s[l:r+1]\n            resLen = r - l + 1\n        l -= 1; r += 1\n    l, r = i, i + 1\n    while l >= 0 and r < len(s) and s[l] == s[r]:\n        if (r - l + 1) > resLen:\n            res = s[l:r+1]\n            resLen = r - l + 1\n        l -= 1; r += 1\nprint(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['babad'], output: ['bab'] },
            { input: ['cbbd'], output: ['bb'] },
            { input: ['a'], output: ['a'] },
            { input: ['ac'], output: ['a'] },
            { input: ['bb'], output: ['bb'] },
            { input: ['ccc'], output: ['ccc'] },
            { input: ['aaaa'], output: ['aaaa'] },
            { input: ['racecar'], output: ['racecar'] },
            { input: ['abacdfgdcaba'], output: ['aba'] },
            { input: ['forgeeksskeegfor'], output: ['geeksskeeg'] },
            { input: ['abacaba'], output: ['abacaba'] },
            { input: ['abccba'], output: ['abccba'] },
            { input: ['abcde'], output: ['a'] },
            { input: ['12321'], output: ['12321'] },
            { input: ['abbcccdddccccbba'], output: ['abbcccdddccccbba'] }
        ],
        videoId: 'XYQecbcd6_c'
    };

