// Batch 4 of problems

export const p31 = {
        id: 'p31',
        title: 'Implement Trie (Prefix Tree)',
        problemStatement: 'Implement a trie (prefix tree) with the following operations:\n- INSERT word: Inserts the string word into the trie.\n- SEARCH word: Returns "true" if the string word is in the trie, "false" otherwise.\n- STARTSWITH prefix: Returns "true" if there is a previously inserted string that has the prefix, "false" otherwise.',
        inputFormat: 'First line: numOps. Next numOps lines contain operations: "INSERT word", "SEARCH word", or "STARTSWITH prefix".',
        outputFormat: 'For each SEARCH and STARTSWITH, print the result on a new line.',
        sampleInput: '5\nINSERT apple\nSEARCH apple\nSEARCH app\nSTARTSWITH app\nINSERT app',
        sampleOutput: 'true\nfalse\ntrue',
        difficulty: 'Medium',
        category: 'Trie',
        constraints: '1 <= word.length, prefix.length <= 2000\nword and prefix consist only of lowercase English letters.\nAt most 3 * 10^4 operations.',
        companies: ['Amazon', 'Google', 'Microsoft', 'Uber'],
        order: 31,
        starterCodes: { python3: '// Implement a Trie data structure\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'rows = int(input())\nmatrix = [list(map(int, input().split())) for _ in range(rows)]\nif not matrix: print("")\nelse:\n    res = []\n    l, r = 0, len(matrix[0])\n    t, b = 0, len(matrix)\n    while l < r and t < b:\n        for i in range(l, r): res.append(matrix[t][i])\n        t += 1\n        for i in range(t, b): res.append(matrix[i][r - 1])\n        r -= 1\n        if not (l < r and t < b): break\n        for i in range(r - 1, l - 1, -1): res.append(matrix[b - 1][i])\n        b -= 1\n        for i in range(b - 1, t - 1, -1): res.append(matrix[i][l])\n        l += 1\n    print(" ".join(map(str, res)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['5', 'INSERT apple', 'SEARCH apple', 'SEARCH app', 'STARTSWITH app', 'INSERT app'], output: ['true', 'false', 'true'] },
            { input: ['4', 'INSERT hello', 'INSERT help', 'STARTSWITH hel', 'SEARCH he'], output: ['true', 'false'] },
            { input: ['2', 'INSERT a', 'SEARCH a'], output: ['true'] },
            { input: ['2', 'INSERT a', 'SEARCH b'], output: ['false'] },
            { input: ['2', 'INSERT abc', 'STARTSWITH a'], output: ['true'] },
            { input: ['2', 'INSERT abc', 'STARTSWITH ab'], output: ['true'] },
            { input: ['2', 'INSERT abc', 'STARTSWITH abc'], output: ['true'] },
            { input: ['2', 'INSERT abc', 'STARTSWITH abcd'], output: ['false'] },
            { input: ['3', 'INSERT apple', 'SEARCH apple', 'SEARCH app'], output: ['true', 'false'] },
            { input: ['4', 'INSERT apple', 'INSERT app', 'SEARCH apple', 'SEARCH app'], output: ['true', 'true'] },
            { input: ['3', 'INSERT a', 'INSERT ab', 'STARTSWITH a'], output: ['true'] },
            { input: ['5', 'INSERT word', 'SEARCH word', 'SEARCH wor', 'STARTSWITH wor', 'SEARCH word'], output: ['true', 'false', 'true', 'true'] },
            { input: ['1', 'SEARCH anything'], output: ['false'] },
            { input: ['1', 'STARTSWITH anything'], output: ['false'] },
            { input: ['4', 'INSERT hot', 'INSERT dog', 'SEARCH hot', 'SEARCH dog'], output: ['true', 'true'] }
        ],
        videoId: 'oobqoCJlHA0'
    };

export const p32 = {
        id: 'p32',
        title: 'Median of Two Sorted Arrays',
        problemStatement: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\n\nThe overall run time complexity should be O(log(m+n)).',
        inputFormat: 'First line: m n. Second line: m sorted integers (or empty). Third line: n sorted integers (or empty).',
        outputFormat: 'Print the median (as a decimal with one decimal place if not integer).',
        sampleInput: '2 2\n1 3\n2 4',
        sampleOutput: '2.5',
        difficulty: 'Hard',
        category: 'Binary Search',
        constraints: 'nums1.length == m\nnums2.length == n\n0 <= m, n <= 1000\n1 <= m + n <= 2000\n-10^6 <= nums1[i], nums2[i] <= 10^6',
        companies: ['Amazon', 'Google', 'Apple', 'Goldman Sachs', 'Adobe'],
        order: 32,
        starterCodes: { python3: '// Find the median of two sorted arrays in O(log(m+n))\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\ndef subsets(nums):\n    res = []\n    subset = []\n    def dfs(i):\n        if i == len(nums):\n            res.append(sorted(subset[:]))\n            return\n        subset.append(nums[i])\n        dfs(i + 1)\n        subset.pop()\n        dfs(i + 1)\n    dfs(0)\n    return sorted(res)\nfor s in subsets(nums): print(" ".join(map(str, s)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['2 2', '1 3', '2 4'], output: ['2.5'] },
            { input: ['2 1', '1 2', '3'], output: ['2.0'] },
            { input: ['1 1', '1', '2'], output: ['1.5'] },
            { input: ['0 1', '', '1'], output: ['1.0'] },
            { input: ['1 0', '2', ''], output: ['2.0'] },
            { input: ['2 2', '1 2', '3 4'], output: ['2.5'] },
            { input: ['2 2', '1 1', '1 1'], output: ['1.0'] },
            { input: ['3 2', '1 3 5', '2 4'], output: ['3.0'] },
            { input: ['1 2', '3', '1 2'], output: ['2.0'] },
            { input: ['5 5', '1 2 3 4 5', '6 7 8 9 10'], output: ['5.5'] },
            { input: ['1 1', '100', '200'], output: ['150.0'] },
            { input: ['2 1', '1 3', '2'], output: ['2.0'] },
            { input: ['1 1', '1', '1'], output: ['1.0'] },
            { input: ['3 3', '1 2 3', '4 5 6'], output: ['3.5'] },
            { input: ['2 3', '1 5', '2 3 4'], output: ['3.0'] }
        ],
        videoId: 'q6IEA26hvXc'
    };

export const p33 = {
        id: 'p33',
        title: 'Matrix Spiral Traversal',
        problemStatement: 'Given an m x n matrix, return all elements of the matrix in spiral order.\n\nSpiral order starts from the top-left corner and moves right, then down, then left, then up, and repeats.',
        inputFormat: 'First line: m n (rows and columns). Next m lines each contain n space-separated integers.',
        outputFormat: 'Print all elements in spiral order, space-separated.',
        sampleInput: '3 3\n1 2 3\n4 5 6\n7 8 9',
        sampleOutput: '1 2 3 6 9 8 7 4 5',
        difficulty: 'Medium',
        category: 'Matrix',
        constraints: 'm == matrix.length\nn == matrix[i].length\n1 <= m, n <= 10\n-100 <= matrix[i][j] <= 100',
        companies: ['Amazon', 'Microsoft', 'Apple', 'Google'],
        order: 33,
        starterCodes: { python3: '// Traverse a matrix in spiral order\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nnums.sort()\nres = []\nfor i in range(len(nums)):\n    if i > 0 and nums[i] == nums[i-1]: continue\n    l, r = i + 1, len(nums) - 1\n    while l < r:\n        s = nums[i] + nums[l] + nums[r]\n        res.append([abs(s), s])\n        if s < 0: l += 1\n        elif s > 0: r -= 1\n        else: break\nres.sort()\nprint(res[0][1])', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3 3', '1 2 3', '4 5 6', '7 8 9'], output: ['1 2 3 6 9 8 7 4 5'] },
            { input: ['3 4', '1 2 3 4', '5 6 7 8', '9 10 11 12'], output: ['1 2 3 4 8 12 11 10 9 5 6 7'] },
            { input: ['1 1', '1'], output: ['1'] },
            { input: ['1 2', '1 2'], output: ['1 2'] },
            { input: ['2 1', '1', '2'], output: ['1 2'] },
            { input: ['2 2', '1 2', '3 4'], output: ['1 2 4 3'] },
            { input: ['4 4', '1 2 3 4', '5 6 7 8', '9 10 11 12', '13 14 15 16'], output: ['1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10'] },
            { input: ['2 3', '1 2 3', '4 5 6'], output: ['1 2 3 6 5 4'] },
            { input: ['3 2', '1 2', '3 4', '5 6'], output: ['1 2 4 6 5 3'] },
            { input: ['1 5', '1 2 3 4 5'], output: ['1 2 3 4 5'] },
            { input: ['5 1', '1', '2', '3', '4', '5'], output: ['1 2 3 4 5'] },
            { input: ['3 3', '1 1 1', '1 1 1', '1 1 1'], output: ['1 1 1 1 1 1 1 1 1'] },
            { input: ['2 4', '1 2 3 4', '5 6 7 8'], output: ['1 2 3 4 8 7 6 5'] },
            { input: ['4 2', '1 2', '3 4', '5 6', '7 8'], output: ['1 2 4 6 8 7 5 3'] },
            { input: ['3 5', '1 2 3 4 5', '6 7 8 9 10', '11 12 13 14 15'], output: ['1 2 3 4 5 10 15 14 13 12 11 6 7 8 9'] }
        ],
        videoId: 'BJnMZNwUk1M'
    };

export const p34 = {
        id: 'p34',
        title: 'House Robber',
        problemStatement: 'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. The only constraint stopping you is that adjacent houses have security systems connected — if two adjacent houses are broken into on the same night, the police will be alerted.\n\nGiven an array representing the amount of money at each house, determine the maximum amount of money you can rob tonight without alerting the police.',
        inputFormat: 'First line: n (number of houses). Second line: n space-separated integers representing money in each house.',
        outputFormat: 'Print the maximum amount of money you can rob.',
        sampleInput: '4\n1 2 3 1',
        sampleOutput: '4',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= n <= 100\n0 <= nums[i] <= 400',
        companies: ['Amazon', 'Google', 'Microsoft', 'Cisco'],
        order: 34,
        starterCodes: { python3: '// Find the maximum money you can rob without robbing adjacent houses\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 's = input().strip()\nt = input().strip()\nif len(t) > len(s): print("")\nelse:\n    countT, window = {}, {}\n    for c in t: countT[c] = 1 + countT.get(c, 0)\n    have, need = 0, len(countT)\n    res, resLen = [-1, -1], float("infinity")\n    l = 0\n    for r in range(len(s)):\n        c = s[r]\n        window[c] = 1 + window.get(c, 0)\n        if c in countT and window[c] == countT[c]: have += 1\n        while have == need:\n            if (r - l + 1) < resLen:\n                res = [l, r]\n                resLen = (r - l + 1)\n            window[s[l]] -= 1\n            if s[l] in countT and window[s[l]] < countT[s[l]]: have -= 1\n            l += 1\n    l, r = res\n    print(s[l:r+1] if resLen != float("infinity") else "")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['4', '1 2 3 1'], output: ['4'] },
            { input: ['5', '2 7 9 3 1'], output: ['12'] },
            { input: ['1', '5'], output: ['5'] },
            { input: ['2', '1 2'], output: ['2'] },
            { input: ['2', '2 1'], output: ['2'] },
            { input: ['3', '1 2 3'], output: ['4'] },
            { input: ['3', '2 1 1'], output: ['3'] },
            { input: ['4', '2 1 1 2'], output: ['4'] },
            { input: ['5', '1 2 3 4 5'], output: ['9'] },
            { input: ['6', '1 1 1 1 1 1'], output: ['3'] },
            { input: ['3', '10 1 1'], output: ['11'] },
            { input: ['4', '1 10 1 1'], output: ['11'] },
            { input: ['5', '1 1 10 1 1'], output: ['12'] },
            { input: ['6', '5 1 1 5 1 1'], output: ['11'] },
            { input: ['2', '0 0'], output: ['0'] }
        ],
        videoId: '73r3KWiEvyk'
    };

export const p35 = {
        id: 'p35',
        title: 'Subsets',
        problemStatement: 'Given an integer array nums of unique elements, return all possible subsets (the power set).\n\nThe solution set must not contain duplicate subsets. Print each subset on a separate line in sorted order. Print subsets in lexicographic order.',
        inputFormat: 'First line: n. Second line: n space-separated integers.',
        outputFormat: 'Print each subset on a separate line as space-separated integers. Empty subset as empty line.',
        sampleInput: '3\n1 2 3',
        sampleOutput: '\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3',
        difficulty: 'Medium',
        category: 'Backtracking',
        constraints: '1 <= n <= 10\n-10 <= nums[i] <= 10\nAll elements are unique.',
        companies: ['Meta', 'Amazon', 'Bloomberg'],
        order: 35,
        starterCodes: { python3: '// Generate all subsets of the given array\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nres = [1] * (len(nums))\nprefix = 1\nfor i in range(len(nums)):\n    res[i] = prefix\n    prefix *= nums[i]\npostfix = 1\nfor i in range(len(nums) - 1, -1, -1):\n    res[i] *= postfix\n    postfix *= nums[i]\nprint(" ".join(map(str, res)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3', '1 2 3'], output: ['', '1', '1 2', '1 2 3', '1 3', '2', '2 3', '3'] },
            { input: ['1', '0'], output: ['', '0'] },
            { input: ['2', '1 2'], output: ['', '1', '1 2', '2'] },
            { input: ['0', ''], output: [''] },
            { input: ['1', '1'], output: ['', '1'] },
            { input: ['3', '0 1 2'], output: ['', '0', '0 1', '0 1 2', '0 2', '1', '1 2', '2'] },
            { input: ['2', '5 10'], output: ['', '5', '5 10', '10'] },
            { input: ['1', '-1'], output: ['', '-1'] },
            { input: ['2', '-1 0'], output: ['', '-1', '-1 0', '0'] },
            { input: ['3', '1 3 2'], output: ['', '1', '1 2', '1 2 3', '1 3', '2', '2 3', '3'] },
            { input: ['2', '3 1'], output: ['', '1', '1 3', '3'] },
            { input: ['1', '100'], output: ['', '100'] },
            { input: ['2', '0 5'], output: ['', '0', '0 5', '5'] },
            { input: ['3', '10 20 30'], output: ['', '10', '10 20', '10 20 30', '10 30', '20', '20 30', '30'] },
            { input: ['2', '2 4'], output: ['', '2', '2 4', '4'] }
        ],
        videoId: 'REOH22Xwdkk'
    };

export const p36 = {
        id: 'p36',
        title: 'Graph BFS Shortest Path',
        problemStatement: 'Given an unweighted undirected graph with V vertices and E edges, find the shortest path distance from a source vertex S to all other vertices using BFS.\n\nIf a vertex is unreachable, print -1 for that vertex.',
        inputFormat: 'First line: V E S. Next E lines each contain: u v (undirected edge).',
        outputFormat: 'Print V space-separated shortest distances from source to each vertex (0 to V-1).',
        sampleInput: '6 7 0\n0 1\n0 2\n1 3\n2 3\n3 4\n4 5\n2 5',
        sampleOutput: '0 1 1 2 3 2',
        difficulty: 'Medium',
        category: 'Graphs',
        constraints: '1 <= V <= 10^4\n0 <= E <= V*(V-1)/2\n0 <= S < V',
        companies: ['Amazon', 'Google', 'Microsoft'],
        order: 36,
        starterCodes: { python3: '// Find shortest paths using BFS in an unweighted graph\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nl, r = 0, n - 1\nwhile l < r:\n    m = (l + r) // 2\n    if nums[m] > nums[r]: l = m + 1\n    else: r = m\nprint(nums[l])', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6 7 0', '0 1', '0 2', '1 3', '2 3', '3 4', '4 5', '2 5'], output: ['0 1 1 2 3 2'] },
            { input: ['4 2 0', '0 1', '2 3'], output: ['0 1 -1 -1'] },
            { input: ['1 0 0'], output: ['0'] },
            { input: ['2 1 0', '0 1'], output: ['0 1'] },
            { input: ['2 1 1', '0 1'], output: ['1 0'] },
            { input: ['3 2 0', '0 1', '1 2'], output: ['0 1 2'] },
            { input: ['3 3 0', '0 1', '1 2', '0 2'], output: ['0 1 1'] },
            { input: ['4 3 0', '0 1', '0 2', '0 3'], output: ['0 1 1 1'] },
            { input: ['5 4 0', '0 1', '1 2', '2 3', '3 4'], output: ['0 1 2 3 4'] },
            { input: ['3 0 0'], output: ['0 -1 -1'] },
            { input: ['4 4 0', '0 1', '1 2', '2 3', '3 0'], output: ['0 1 2 1'] },
            { input: ['5 5 0', '0 1', '1 2', '2 3', '3 4', '4 0'], output: ['0 1 2 2 1'] },
            { input: ['2 0 0'], output: ['0 -1'] },
            { input: ['3 1 1', '0 1'], output: ['1 0 -1'] },
            { input: ['4 6 0', '0 1', '0 2', '0 3', '1 2', '1 3', '2 3'], output: ['0 1 1 1'] }
        ],
        videoId: 'oDqjPvD54Ss'
    };

export const p37 = {
        id: 'p37',
        title: 'Min Stack',
        problemStatement: 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.\n\nImplement the MinStack with operations:\n- PUSH val: Push val onto the stack.\n- POP: Remove the top element.\n- TOP: Get the top element.\n- GETMIN: Retrieve the minimum element in the stack.',
        inputFormat: 'First line: numOps. Next numOps lines contain operations.',
        outputFormat: 'For TOP and GETMIN operations, print the result on a new line.',
        sampleInput: '7\nPUSH -2\nPUSH 0\nPUSH -3\nGETMIN\nPOP\nTOP\nGETMIN',
        sampleOutput: '-3\n0\n-2',
        difficulty: 'Medium',
        category: 'Stacks',
        constraints: '-2^31 <= val <= 2^31 - 1\nMethods pop, top and getMin will always be called on non-empty stacks.\nAt most 3 * 10^4 calls.',
        companies: ['Amazon', 'Bloomberg', 'Goldman Sachs'],
        order: 37,
        starterCodes: { python3: '// Implement a stack with O(1) minimum retrieval\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n, target = map(int, input().split())\nnums = list(map(int, input().split()))\nl, r = 0, n - 1\nres = -1\nwhile l <= r:\n    m = (l + r) // 2\n    if target == nums[m]: res = m; break\n    if nums[l] <= nums[m]:\n        if target > nums[m] or target < nums[l]: l = m + 1\n        else: r = m - 1\n    else:\n        if target < nums[m] or target > nums[r]: r = m - 1\n        else: l = m + 1\nprint(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['7', 'PUSH -2', 'PUSH 0', 'PUSH -3', 'GETMIN', 'POP', 'TOP', 'GETMIN'], output: ['-3', '0', '-2'] },
            { input: ['4', 'PUSH 1', 'PUSH 2', 'TOP', 'GETMIN'], output: ['2', '1'] },
            { input: ['5', 'PUSH 1', 'PUSH 2', 'POP', 'TOP', 'GETMIN'], output: ['1', '1'] },
            { input: ['6', 'PUSH 5', 'PUSH 3', 'PUSH 7', 'GETMIN', 'POP', 'GETMIN'], output: ['3', '3'] },
            { input: ['4', 'PUSH 10', 'GETMIN', 'PUSH 5', 'GETMIN'], output: ['10', '5'] },
            { input: ['2', 'PUSH -1', 'GETMIN'], output: ['-1'] },
            { input: ['3', 'PUSH 1', 'POP', 'PUSH 2'], output: [] },
            { input: ['6', 'PUSH 1', 'PUSH 2', 'PUSH 3', 'GETMIN', 'POP', 'GETMIN'], output: ['1', '1'] },
            { input: ['6', 'PUSH 3', 'PUSH 2', 'PUSH 1', 'GETMIN', 'POP', 'GETMIN'], output: ['1', '2'] },
            { input: ['4', 'PUSH 0', 'PUSH 1', 'PUSH 0', 'GETMIN'], output: ['0'] },
            { input: ['5', 'PUSH 0', 'PUSH 1', 'PUSH 0', 'GETMIN', 'POP'], output: ['0'] },
            { input: ['6', 'PUSH 0', 'PUSH 1', 'PUSH 0', 'GETMIN', 'POP', 'GETMIN'], output: ['0', '0'] },
            { input: ['5', 'PUSH -10', 'PUSH 20', 'GETMIN', 'TOP', 'GETMIN'], output: ['-10', '20', '-10'] },
            { input: ['3', 'PUSH 100', 'TOP', 'GETMIN'], output: ['100', '100'] },
            { input: ['4', 'PUSH 1', 'PUSH 1', 'GETMIN', 'POP'], output: ['1'] }
        ],
        videoId: 'qkLl7nAwDPo'
    };

export const p38 = {
        id: 'p38',
        title: '0/1 Knapsack',
        problemStatement: 'Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack.\n\nEach item can either be included or excluded (0/1 property) — you cannot break an item or include it more than once.',
        inputFormat: 'First line: n W (number of items and knapsack capacity). Second line: n space-separated weights. Third line: n space-separated values.',
        outputFormat: 'Print the maximum value that can be obtained.',
        sampleInput: '3 50\n10 20 30\n60 100 120',
        sampleOutput: '220',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= n <= 100\n1 <= W <= 1000\n1 <= weight[i], value[i] <= 1000',
        companies: ['Amazon', 'Google', 'Microsoft', 'Goldman Sachs'],
        order: 38,
        starterCodes: { python3: '// Solve the 0/1 Knapsack problem using dynamic programming\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\ndef permute(nums):\n    res = []\n    if len(nums) == 1: return [nums[:]]\n    for i in range(len(nums)):\n        n = nums.pop(0)\n        perms = permute(nums)\n        for p in perms: p.append(n)\n        res.extend(perms)\n        nums.append(n)\n    return res\nfor p in sorted(permute(nums)): print(" ".join(map(str, p)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3 50', '10 20 30', '60 100 120'], output: ['220'] },
            { input: ['4 7', '1 3 4 5', '1 4 5 7'], output: ['9'] },
            { input: ['1 1', '2', '10'], output: ['0'] },
            { input: ['1 10', '5', '100'], output: ['100'] },
            { input: ['2 10', '5 5', '10 20'], output: ['30'] },
            { input: ['2 4', '5 5', '10 20'], output: ['0'] },
            { input: ['3 10', '1 2 3', '10 20 30'], output: ['60'] },
            { input: ['3 2', '1 1 1', '10 20 30'], output: ['50'] },
            { input: ['5 10', '1 2 3 4 5', '1 2 3 4 5'], output: ['10'] },
            { input: ['2 100', '50 50', '10 10'], output: ['20'] },
            { input: ['3 100', '101 102 103', '1 2 3'], output: ['0'] },
            { input: ['3 10', '5 4 6', '10 8 12'], output: ['20'] },
            { input: ['4 5', '1 2 3 4', '2 4 4 5'], output: ['8'] },
            { input: ['2 1', '1 1', '10 20'], output: ['20'] },
            { input: ['5 100', '20 30 40 50 60', '40 50 60 70 80'], output: ['150'] }
        ],
        videoId: 'xOlhR_2QCQQ'
    };

export const p39 = {
        id: 'p39',
        title: 'Serialize and Deserialize Binary Tree',
        problemStatement: 'Design an algorithm to serialize and deserialize a binary tree.\n\nSerialization is converting a tree to a string. Deserialization is reconstructing the tree from the string.\n\nGiven a binary tree as level-order input (-1 for null), serialize it to a string and then deserialize it back. Print the level-order traversal of the deserialized tree to verify correctness.',
        inputFormat: 'First line: n (number of elements in level-order). Second line: n space-separated integers (-1 for null).',
        outputFormat: 'Print the level-order traversal of the tree after serialize → deserialize (excluding trailing nulls).',
        sampleInput: '7\n1 2 3 -1 -1 4 5',
        sampleOutput: '1 2 3 -1 -1 4 5',
        difficulty: 'Hard',
        category: 'Trees',
        constraints: 'The number of nodes is in [0, 10^4].\n-1000 <= Node.val <= 1000',
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'LinkedIn'],
        order: 39,
        starterCodes: { python3: '// Implement serialize and deserialize for a binary tree\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nif not nums: print("false")\nelse:\n    goal = len(nums) - 1\n    for i in range(len(nums) - 1, -1, -1):\n        if i + nums[i] >= goal: goal = i\n    print("true" if goal == 0 else "false")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['7', '1 2 3 -1 -1 4 5'], output: ['1 2 3 -1 -1 4 5'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['0', ''], output: [''] },
            { input: ['3', '1 2 3'], output: ['1 2 3'] },
            { input: ['3', '1 2 -1'], output: ['1 2'] },
            { input: ['3', '1 -1 2'], output: ['1 -1 2'] },
            { input: ['7', '1 2 3 4 5 6 7'], output: ['1 2 3 4 5 6 7'] },
            { input: ['15', '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15'], output: ['1 2 3 4 5 6 7 8 9 10 11 12 13 14 15'] },
            { input: ['2', '1 2'], output: ['1 2'] },
            { input: ['2', '1 -1'], output: ['1'] },
            { input: ['4', '1 2 3 4'], output: ['1 2 3 4'] },
            { input: ['5', '1 2 3 -1 4'], output: ['1 2 3 -1 4'] },
            { input: ['7', '1 2 3 4 -1 5 6'], output: ['1 2 3 4 -1 5 6'] },
            { input: ['4', '1 -1 2 -1 3'], output: ['1 -1 2 -1 3'] },
            { input: ['5', '1 2 -1 3 -1 4'], output: ['1 2 -1 3 -1 4'] }
        ],
        videoId: 'u4JAi2JJhI8'
    };

export const p40 = {
        id: 'p40',
        title: 'Longest Increasing Subsequence',
        problemStatement: 'Given an integer array nums, return the length of the longest strictly increasing subsequence.\n\nA subsequence is derived from an array by deleting some or no elements without changing the order of the remaining elements.',
        inputFormat: 'First line: n. Second line: n space-separated integers.',
        outputFormat: 'Print the length of the longest strictly increasing subsequence.',
        sampleInput: '8\n10 9 2 5 3 7 101 18',
        sampleOutput: '4',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= n <= 2500\n-10^4 <= nums[i] <= 10^4',
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
        order: 40,
        starterCodes: { python3: '// Find the length of the longest increasing subsequence\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nmatrix = [list(map(int, input().split())) for _ in range(n)]\nl, r = 0, n - 1\nwhile l < r:\n    for i in range(r - l):\n        t, b = l, r\n        topLeft = matrix[t][l + i]\n        matrix[t][l + i] = matrix[b - i][l]\n        matrix[b - i][l] = matrix[b][r - i]\n        matrix[b][r - i] = matrix[t + i][r]\n        matrix[t + i][r] = topLeft\n    r -= 1; l += 1\nfor row in matrix: print(" ".join(map(str, row)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['8', '10 9 2 5 3 7 101 18'], output: ['4'] },
            { input: ['6', '0 1 0 3 2 3'], output: ['4'] },
            { input: ['7', '7 7 7 7 7 7 7'], output: ['1'] },
            { input: ['1', '10'], output: ['1'] },
            { input: ['2', '1 2'], output: ['2'] },
            { input: ['2', '2 1'], output: ['1'] },
            { input: ['5', '1 2 3 4 5'], output: ['5'] },
            { input: ['5', '5 4 3 2 1'], output: ['1'] },
            { input: ['6', '1 3 2 4 6 5'], output: ['4'] },
            { input: ['10', '1 2 3 4 5 6 7 8 9 10'], output: ['10'] },
            { input: ['10', '10 9 8 7 6 5 4 3 2 1'], output: ['1'] },
            { input: ['4', '1 5 2 3'], output: ['3'] },
            { input: ['5', '3 4 -1 0 6'], output: ['4'] },
            { input: ['6', '2 5 3 7 11 8'], output: ['4'] },
            { input: ['3', '1 1 1'], output: ['1'] }
        ],
        videoId: 'CE2b_-XfVDk'
    };

