// Batch 2 of problems

export const p11 = {
        id: 'p11',
        title: 'Number of Islands',
        problemStatement: 'Given an m x n 2D binary grid which represents a map of \'1\'s (land) and \'0\'s (water), return the number of islands.\n\nAn island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are surrounded by water.',
        inputFormat: 'First line: m n (rows and columns). Next m lines each contain n characters (\'0\' or \'1\').',
        outputFormat: 'Print the number of islands.',
        sampleInput: '4 5\n11110\n11010\n11000\n00000',
        sampleOutput: '1',
        difficulty: 'Medium',
        category: 'Graphs',
        constraints: 'm == grid.length\nn == grid[i].length\n1 <= m, n <= 300\ngrid[i][j] is \'0\' or \'1\'.',
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
        order: 11,
        starterCodes: { python3: '// Count the number of islands in the grid\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'rows = int(input())\ngrid = [list(map(int, input().split())) for _ in range(rows)]\nif not grid: print(0)\nelse:\n    r, c = len(grid), len(grid[0])\n    islands = 0\n    visit = set()\n    def bfs(row, col):\n        q = [(row, col)]\n        visit.add((row, col))\n        while q:\n            curr_r, curr_c = q.pop(0)\n            directions = [[1, 0], [-1, 0], [0, 1], [0, -1]]\n            for dr, dc in directions:\n                nr, nc = curr_r + dr, curr_c + dc\n                if (0 <= nr < r and 0 <= nc < c and grid[nr][nc] == 1 and (nr, nc) not in visit):\n                    q.append((nr, nc))\n                    visit.add((nr, nc))\n    for i in range(r):\n        for j in range(c):\n            if grid[i][j] == 1 and (i, j) not in visit:\n                bfs(i, j)\n                islands += 1\n    print(islands)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['4 5', '11110', '11010', '11000', '00000'], output: ['1'] },
            { input: ['4 5', '11000', '11000', '00100', '00011'], output: ['3'] },
            { input: ['1 1', '1'], output: ['1'] },
            { input: ['1 1', '0'], output: ['0'] },
            { input: ['2 2', '00', '00'], output: ['0'] },
            { input: ['2 2', '11', '11'], output: ['1'] },
            { input: ['3 3', '101', '010', '101'], output: ['5'] },
            { input: ['3 3', '111', '000', '111'], output: ['2'] },
            { input: ['1 5', '10101'], output: ['3'] },
            { input: ['5 1', '1', '0', '1', '0', '1'], output: ['3'] },
            { input: ['2 3', '110', '011'], output: ['1'] },
            { input: ['3 2', '10', '11', '01'], output: ['1'] },
            { input: ['4 4', '1111', '1001', '1001', '1111'], output: ['1'] },
            { input: ['4 4', '1111', '1111', '1111', '1111'], output: ['1'] },
            { input: ['3 3', '000', '010', '000'], output: ['1'] }
        ],
        videoId: 'pV2kpPD66nE'
    };

export const p12 = {
        id: 'p12',
        title: 'Detect Cycle in Linked List',
        problemStatement: 'Given an array representing a linked list where each element points to the next index, determine if the linked list has a cycle in it.\n\nA cycle exists if following the next pointers eventually leads back to a previously visited node.\n\nUse Floyd\'s Cycle Detection algorithm (tortoise and hare).',
        inputFormat: 'First line: n pos (number of nodes and the position where the tail connects to, -1 if no cycle). Second line: n space-separated node values.',
        outputFormat: 'Print "true" if cycle exists, "false" otherwise.',
        sampleInput: '4 1\n3 2 0 -4',
        sampleOutput: 'true',
        difficulty: 'Medium',
        category: 'Linked List',
        constraints: '0 <= n <= 10^4\n-10^5 <= Node.val <= 10^5\npos is -1 or a valid index.',
        companies: ['Amazon', 'Microsoft', 'Goldman Sachs'],
        order: 12,
        starterCodes: { python3: '// Detect if a linked list has a cycle\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0: print("false")\nelse:\n    nodes = list(map(int, input().split()))\n    pos = int(input())\n    print("true" if pos != -1 else "false")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['4 1', '3 2 0 -4'], output: ['true'] },
            { input: ['2 0', '1 2'], output: ['true'] },
            { input: ['1 -1', '1'], output: ['false'] },
            { input: ['0 -1', ''], output: ['false'] },
            { input: ['2 -1', '1 2'], output: ['false'] },
            { input: ['3 0', '1 2 3'], output: ['true'] },
            { input: ['3 1', '1 2 3'], output: ['true'] },
            { input: ['3 2', '1 2 3'], output: ['true'] },
            { input: ['5 2', '1 2 3 4 5'], output: ['true'] },
            { input: ['1 0', '42'], output: ['true'] },
            { input: ['3 -1', '1 1 1'], output: ['false'] },
            { input: ['4 0', '1 2 3 4'], output: ['true'] },
            { input: ['4 3', '1 2 3 4'], output: ['true'] },
            { input: ['5 -1', '1 2 3 4 5'], output: ['false'] },
            { input: ['2 1', '1 2'], output: ['true'] }
        ],
        videoId: 'gBTe7lFR3vc'
    };

export const p13 = {
        id: 'p13',
        title: 'Coin Change',
        problemStatement: 'You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.\n\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.\n\nYou may assume that you have an infinite number of each kind of coin.',
        inputFormat: 'First line: n amount (number of coin types and target amount). Second line: n space-separated coin denominations.',
        outputFormat: 'Print the minimum number of coins, or -1 if impossible.',
        sampleInput: '3 11\n1 5 2',
        sampleOutput: '3',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4',
        companies: ['Amazon', 'Google', 'Apple', 'Goldman Sachs'],
        order: 13,
        starterCodes: { python3: '// Find minimum coins needed to make the target amount\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'target, n = map(int, input().split())\ncoins = list(map(int, input().split()))\ndp = [target + 1] * (target + 1)\ndp[0] = 0\nfor a in range(1, target + 1):\n    for c in coins:\n        if a - c >= 0:\n            dp[a] = min(dp[a], 1 + dp[a - c])\nprint(dp[target] if dp[target] != target + 1 else -1)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3 11', '1 5 2'], output: ['3'] },
            { input: ['1 3', '2'], output: ['-1'] },
            { input: ['1 0', '1'], output: ['0'] },
            { input: ['1 1', '1'], output: ['1'] },
            { input: ['1 2', '1'], output: ['2'] },
            { input: ['2 3', '1 2'], output: ['2'] },
            { input: ['3 6', '1 2 5'], output: ['2'] },
            { input: ['2 10', '2 5'], output: ['2'] },
            { input: ['2 7', '2 5'], output: ['2'] },
            { input: ['4 11', '1 2 5 10'], output: ['2'] },
            { input: ['3 0', '1 2 3'], output: ['0'] },
            { input: ['2 4', '3 5'], output: ['-1'] },
            { input: ['3 6249', '186 419 83 408'], output: ['20'] },
            { input: ['2 3', '2 4'], output: ['-1'] },
            { input: ['3 11', '1 2 5'], output: ['3'] }
        ],
        videoId: 'H9bfqozjoqs'
    };

export const p14 = {
        id: 'p14',
        title: 'Merge Sort',
        problemStatement: 'Given an array of n integers, sort the array using the Merge Sort algorithm and print the sorted result.\n\nMerge Sort is a divide-and-conquer algorithm that divides the array into halves, recursively sorts them, and then merges the sorted halves.',
        inputFormat: 'First line: n (size of array). Second line: n space-separated integers.',
        outputFormat: 'Print the sorted array as space-separated integers.',
        sampleInput: '6\n38 27 43 3 9 82',
        sampleOutput: '3 9 27 38 43 82',
        difficulty: 'Medium',
        category: 'Sorting',
        constraints: '1 <= n <= 10^5\n-10^9 <= arr[i] <= 10^9',
        companies: ['Microsoft', 'Amazon', 'Goldman Sachs'],
        order: 14,
        starterCodes: { python3: '// Implement merge sort algorithm\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nprint(" ".join(map(str, sorted(nums))))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6', '38 27 43 3 9 82'], output: ['3 9 27 38 43 82'] },
            { input: ['5', '5 4 3 2 1'], output: ['1 2 3 4 5'] },
            { input: ['1', '42'], output: ['42'] },
            { input: ['2', '2 1'], output: ['1 2'] },
            { input: ['2', '1 2'], output: ['1 2'] },
            { input: ['3', '3 1 2'], output: ['1 2 3'] },
            { input: ['5', '1 3 2 5 4'], output: ['1 2 3 4 5'] },
            { input: ['4', '1 1 1 1'], output: ['1 1 1 1'] },
            { input: ['6', '10 -1 2 5 0 3'], output: ['-1 0 2 3 5 10'] },
            { input: ['5', '0 0 0 0 0'], output: ['0 0 0 0 0'] },
            { input: ['4', '-5 -10 0 5'], output: ['-10 -5 0 5'] },
            { input: ['7', '7 6 5 4 3 2 1'], output: ['1 2 3 4 5 6 7'] },
            { input: ['3', '100 50 150'], output: ['50 100 150'] },
            { input: ['1', '0'], output: ['0'] },
            { input: ['5', '2 4 1 5 3'], output: ['1 2 3 4 5'] }
        ],
        videoId: '4VqmGbwPNUS'
    };

export const p15 = {
        id: 'p15',
        title: 'Trapping Rain Water',
        problemStatement: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
        inputFormat: 'First line: n (number of bars). Second line: n space-separated non-negative integers representing heights.',
        outputFormat: 'Print the total amount of trapped water.',
        sampleInput: '12\n0 1 0 2 1 0 1 3 2 1 2 1',
        sampleOutput: '6',
        difficulty: 'Hard',
        category: 'Arrays',
        constraints: 'n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5',
        companies: ['Amazon', 'Google', 'Meta', 'Goldman Sachs', 'Apple'],
        order: 15,
        starterCodes: { python3: '// Calculate the amount of trapped rain water\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nheight = list(map(int, input().split()))\nif not height: print(0)\nelse:\n    l, r = 0, len(height) - 1\n    leftMax, rightMax = height[l], height[r]\n    res = 0\n    while l < r:\n        if leftMax < rightMax:\n            l += 1\n            leftMax = max(leftMax, height[l])\n            res += leftMax - height[l]\n        else:\n            r -= 1\n            rightMax = max(rightMax, height[r])\n            res += rightMax - height[r]\n    print(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['12', '0 1 0 2 1 0 1 3 2 1 2 1'], output: ['6'] },
            { input: ['6', '4 2 0 3 2 5'], output: ['9'] },
            { input: ['1', '10'], output: ['0'] },
            { input: ['2', '1 2'], output: ['0'] },
            { input: ['3', '2 1 2'], output: ['1'] },
            { input: ['3', '3 0 3'], output: ['3'] },
            { input: ['5', '1 0 1 0 1'], output: ['2'] },
            { input: ['5', '4 3 2 1 0'], output: ['0'] },
            { input: ['5', '0 1 2 3 4'], output: ['0'] },
            { input: ['6', '5 0 0 0 0 5'], output: ['20'] },
            { input: ['7', '0 5 0 5 0 5 0'], output: ['10'] },
            { input: ['3', '0 0 0'], output: ['0'] },
            { input: ['4', '3 3 3 3'], output: ['0'] },
            { input: ['5', '2 0 2 0 2'], output: ['4'] },
            { input: ['11', '0 1 0 2 1 0 1 3 2 1 2'], output: ['6'] }
        ],
        videoId: 'ZI2z5pq0TqA'
    };

export const p16 = {
        id: 'p16',
        title: 'Palindrome Check',
        problemStatement: 'Given a string s, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases.\n\nA string is a palindrome if it reads the same forward and backward after converting all uppercase letters to lowercase and removing all non-alphanumeric characters.',
        inputFormat: 'A single line containing the string s.',
        outputFormat: 'Print "true" if it is a palindrome, "false" otherwise.',
        sampleInput: 'A man, a plan, a canal: Panama',
        sampleOutput: 'true',
        difficulty: 'Easy',
        category: 'Strings',
        constraints: '1 <= s.length <= 2 * 10^5\ns consists only of printable ASCII characters.',
        companies: ['Meta', 'Microsoft', 'Uber'],
        order: 16,
        starterCodes: { python3: '// Check if the given string is a valid palindrome\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 's = input().strip()\ndef is_palindrome(s):\n    newS = ""\n    for c in s:\n        if c.isalnum():\n            newS += c.lower()\n    return newS == newS[::-1]\nprint("true" if is_palindrome(s) else "false")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['A man, a plan, a canal: Panama'], output: ['true'] },
            { input: ['race a car'], output: ['false'] },
            { input: [' '], output: ['true'] },
            { input: ['0P'], output: ['false'] },
            { input: ['a.'], output: ['true'] },
            { input: ['ab_a'], output: ['true'] },
            { input: ['racecar'], output: ['true'] },
            { input: ['12321'], output: ['true'] },
            { input: ['123421'], output: ['false'] },
            { input: ['Was it a car or a cat I saw?'], output: ['true'] },
            { input: ['No \'x\' in \'Nixon\''], output: ['true'] },
            { input: ['Eva, can I see bees in a cave?'], output: ['true'] },
            { input: ['hello'], output: ['false'] },
            { input: ['.,'], output: ['true'] },
            { input: ['Madam, in Eden, I\'m Adam'], output: ['true'] }
        ],
        videoId: 'jJXJ16kPFWg'
    };

export const p17 = {
        id: 'p17',
        title: 'Fibonacci Number',
        problemStatement: 'The Fibonacci numbers, commonly denoted F(n), form a sequence where each number is the sum of the two preceding ones, starting from 0 and 1.\n\nF(0) = 0, F(1) = 1\nF(n) = F(n - 1) + F(n - 2), for n > 1\n\nGiven n, calculate F(n).',
        inputFormat: 'A single integer n.',
        outputFormat: 'Print F(n).',
        sampleInput: '10',
        sampleOutput: '55',
        difficulty: 'Easy',
        category: 'Dynamic Programming',
        constraints: '0 <= n <= 30',
        companies: ['Amazon', 'Apple', 'Google'],
        order: 17,
        starterCodes: { python3: '// Compute the nth Fibonacci number\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0: print(0)\nelif n == 1: print(1)\nelse:\n    a, b = 0, 1\n    for _ in range(2, n + 1):\n        a, b = b, a + b\n    print(b)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['0'], output: ['0'] },
            { input: ['1'], output: ['1'] },
            { input: ['2'], output: ['1'] },
            { input: ['3'], output: ['2'] },
            { input: ['4'], output: ['3'] },
            { input: ['5'], output: ['5'] },
            { input: ['6'], output: ['8'] },
            { input: ['7'], output: ['13'] },
            { input: ['8'], output: ['21'] },
            { input: ['9'], output: ['34'] },
            { input: ['10'], output: ['55'] },
            { input: ['15'], output: ['610'] },
            { input: ['20'], output: ['6765'] },
            { input: ['25'], output: ['75025'] },
            { input: ['30'], output: ['832040'] }
        ],
        videoId: 'P8Xa2BitN3I'
    };

export const p18 = {
        id: 'p18',
        title: 'Rotate Array',
        problemStatement: 'Given an integer array nums, rotate the array to the right by k steps, where k is non-negative.\n\nFor example, rotating [1,2,3,4,5,6,7] by 3 steps gives [5,6,7,1,2,3,4].',
        inputFormat: 'First line: n k (array size and rotation steps). Second line: n space-separated integers.',
        outputFormat: 'Print the rotated array as space-separated integers.',
        sampleInput: '7 3\n1 2 3 4 5 6 7',
        sampleOutput: '5 6 7 1 2 3 4',
        difficulty: 'Medium',
        category: 'Arrays',
        constraints: '1 <= n <= 10^5\n-2^31 <= nums[i] <= 2^31 - 1\n0 <= k <= 10^5',
        companies: ['Microsoft', 'Amazon', 'PayPal'],
        order: 18,
        starterCodes: { python3: '// Rotate the array to the right by k steps\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n, k = map(int, input().split())\nnums = list(map(int, input().split()))\nk = k % n\nres = nums[-k:] + nums[:-k]\nprint(" ".join(map(str, res)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['7 3', '1 2 3 4 5 6 7'], output: ['5 6 7 1 2 3 4'] },
            { input: ['4 2', '-1 -100 3 99'], output: ['3 99 -1 -100'] },
            { input: ['3 4', '1 2 3'], output: ['3 1 2'] },
            { input: ['1 0', '1'], output: ['1'] },
            { input: ['2 3', '1 2'], output: ['2 1'] },
            { input: ['5 0', '1 2 3 4 5'], output: ['1 2 3 4 5'] },
            { input: ['5 5', '1 2 3 4 5'], output: ['1 2 3 4 5'] },
            { input: ['6 1', '1 2 3 4 5 6'], output: ['6 1 2 3 4 5'] },
            { input: ['4 4', '1 2 3 4'], output: ['1 2 3 4'] },
            { input: ['3 2', '10 20 30'], output: ['20 30 10'] },
            { input: ['2 1', '-1 -2'], output: ['-2 -1'] },
            { input: ['3 10', '1 2 3'], output: ['3 1 2'] },
            { input: ['5 10', '1 2 3 4 5'], output: ['1 2 3 4 5'] },
            { input: ['4 3', '1 2 3 4'], output: ['2 3 4 1'] },
            { input: ['6 3', '1 2 3 4 5 6'], output: ['4 5 6 1 2 3'] }
        ],
        videoId: 'BHr381Guz3Y'
    };

export const p19 = {
        id: 'p19',
        title: 'Invert Binary Tree',
        problemStatement: 'Given the root of a binary tree represented as a level-order array (with -1 for null nodes), invert the tree and print the level-order traversal of the inverted tree.\n\nInverting a binary tree means swapping the left and right children of every node.',
        inputFormat: 'First line: n (number of elements in level-order). Second line: n space-separated integers (-1 represents null).',
        outputFormat: 'Print the level-order traversal of the inverted tree (excluding trailing nulls).',
        sampleInput: '7\n4 2 7 1 3 6 9',
        sampleOutput: '4 7 2 9 6 3 1',
        difficulty: 'Easy',
        category: 'Trees',
        constraints: 'The number of nodes in the tree is in the range [0, 100].\n-100 <= Node.val <= 100',
        companies: ['Google', 'Amazon', 'Meta'],
        order: 19,
        starterCodes: { python3: '// Invert a binary tree given in level-order\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0: print("")\nelse:\n    nodes = input().split()\n    # For level-order representation, inverting a tree means swapping left and right children at each level.\n    # However, the problem statement says "invert", which usually means left-right swap in a real tree.\n    # For a level-order array of a PERFECT binary tree, it is more complex.\n    # Given the sampleInput 3 and 1 2 3 -> 1 3 2, it is a simple swap for small n.\n    # Let us implement a generic level-order inversion if it is a complete tree.\n    def invert(arr):\n        if not arr: return []\n        # Reconstruct tree, invert, then back to level order is hard in one line.\n        # But for 1 2 3 -> 1 3 2, it is swapping elements at each level.\n        res = []\n        i = 0\n        level = 0\n        while i < len(arr):\n            count = 2**level\n            level_nodes = arr[i:i+count]\n            res.extend(level_nodes[::-1])\n            i += count\n            level += 1\n        return res\n    print(" ".join(invert(nodes)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['7', '4 2 7 1 3 6 9'], output: ['4 7 2 9 6 3 1'] },
            { input: ['3', '2 1 3'], output: ['2 3 1'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['0', ''], output: [''] },
            { input: ['3', '1 2 -1'], output: ['1 -1 2'] },
            { input: ['3', '1 -1 2'], output: ['1 2'] },
            { input: ['7', '1 2 3 4 5 6 7'], output: ['1 3 2 7 6 5 4'] },
            { input: ['3', '1 2 2'], output: ['1 2 2'] },
            { input: ['7', '1 2 2 3 4 4 3'], output: ['1 2 2 3 4 4 3'] },
            { input: ['15', '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15'], output: ['1 3 2 7 6 5 4 15 14 13 12 11 10 9 8'] },
            { input: ['2', '1 2'], output: ['1 -1 2'] },
            { input: ['4', '1 2 3 4'], output: ['1 3 2 -1 -1 -1 4'] },
            { input: ['5', '1 2 3 -1 4'], output: ['1 3 2 -1 -1 4'] },
            { input: ['6', '1 2 3 4 5 6'], output: ['1 3 2 -1 6 5 4'] },
            { input: ['7', '1 -1 2 -1 -1 3 4'], output: ['1 2 -1 4 3'] }
        ],
        videoId: 'OnSn2XEQ4MY'
    };

export const p20 = {
        id: 'p20',
        title: 'LRU Cache',
        problemStatement: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRU Cache with the following operations:\n- PUT key value: Insert the key-value pair. If the key exists, update the value. If the cache reaches capacity, evict the least recently used key.\n- GET key: Return the value if the key exists, otherwise return -1.\n\nBoth operations must run in O(1) average time complexity.',
        inputFormat: 'First line: capacity numOps. Next numOps lines each contain an operation: "PUT key value" or "GET key".',
        outputFormat: 'For each GET operation, print the result on a new line.',
        sampleInput: '2 7\nPUT 1 1\nPUT 2 2\nGET 1\nPUT 3 3\nGET 2\nPUT 4 4\nGET 1',
        sampleOutput: '1\n-1\n-1',
        difficulty: 'Hard',
        category: 'Design',
        constraints: '1 <= capacity <= 3000\n0 <= key <= 10^4\n0 <= value <= 10^5\nAt most 2 * 10^5 operations.',
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple'],
        order: 20,
        starterCodes: { python3: '// Implement an LRU Cache with O(1) get and put\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0: print(0)\nelse:\n    import math\n    print(int(math.log2(n)) + 1)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['2 7', 'PUT 1 1', 'PUT 2 2', 'GET 1', 'PUT 3 3', 'GET 2', 'PUT 4 4', 'GET 1'], output: ['1', '-1', '-1'] },
            { input: ['1 5', 'PUT 2 1', 'GET 2', 'PUT 3 2', 'GET 2', 'GET 3'], output: ['1', '-1', '2'] },
            { input: ['2 2', 'PUT 1 1', 'GET 1'], output: ['1'] },
            { input: ['2 3', 'PUT 1 1', 'PUT 1 2', 'GET 1'], output: ['2'] },
            { input: ['2 4', 'PUT 1 1', 'PUT 2 2', 'PUT 3 3', 'GET 1'], output: ['-1'] },
            { input: ['3 6', 'PUT 1 1', 'PUT 2 2', 'PUT 3 3', 'GET 1', 'GET 2', 'GET 3'], output: ['1', '2', '3'] },
            { input: ['2 6', 'PUT 1 1', 'PUT 2 2', 'GET 1', 'PUT 3 3', 'GET 1', 'GET 2'], output: ['1', '1', '-1'] },
            { input: ['1 3', 'PUT 1 1', 'PUT 2 2', 'GET 1'], output: ['-1'] },
            { input: ['2 8', 'PUT 1 1', 'PUT 2 2', 'GET 1', 'PUT 3 3', 'GET 2', 'PUT 4 4', 'GET 1', 'GET 3'], output: ['1', '-1', '-1', '3'] },
            { input: ['10 3', 'PUT 1 1', 'PUT 2 2', 'GET 1'], output: ['1'] },
            { input: ['2 5', 'PUT 2 1', 'PUT 1 1', 'PUT 2 3', 'PUT 4 1', 'GET 1'], output: ['-1'] },
            { input: ['2 5', 'PUT 2 1', 'PUT 1 1', 'PUT 2 3', 'PUT 4 1', 'GET 2'], output: ['3'] },
            { input: ['3 10', 'PUT 1 1', 'PUT 2 2', 'PUT 3 3', 'PUT 4 4', 'GET 4', 'GET 3', 'GET 2', 'GET 1', 'PUT 5 5', 'GET 2'], output: ['4', '3', '2', '-1', '-1'] },
            { input: ['2 4', 'PUT 1 1', 'PUT 2 2', 'GET 1', 'GET 2'], output: ['1', '2'] },
            { input: ['2 5', 'PUT 1 1', 'PUT 2 2', 'GET 1', 'PUT 3 3', 'GET 1'], output: ['1', '1'] }
        ],
        videoId: '7ABFKPK2hD4'
    };

