// Batch 5 of problems

export const p41 = {
        id: 'p41',
        title: 'Find Median from Data Stream',
        problemStatement: 'Design a data structure that supports adding integers from a data stream and finding the median of all elements added so far.\n\nImplement:\n- ADD num: Add num to the data structure.\n- MEDIAN: Return the median of all elements.\n\nIf the count is even, the median is the average of the two middle values.',
        inputFormat: 'First line: numOps. Next numOps lines contain operations: "ADD num" or "MEDIAN".',
        outputFormat: 'For each MEDIAN operation, print the result (one decimal place if not integer).',
        sampleInput: '7\nADD 1\nADD 2\nMEDIAN\nADD 3\nMEDIAN\nADD 4\nMEDIAN',
        sampleOutput: '1.5\n2.0\n2.5',
        difficulty: 'Hard',
        category: 'Heap',
        constraints: '-10^5 <= num <= 10^5\nThere will be at least one element before MEDIAN is called.\nAt most 5 * 10^4 operations.',
        companies: ['Amazon', 'Google', 'Apple', 'Meta'],
        order: 41,
        starterCodes: { python3: '// Find median from a data stream using heaps\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0: print("0 0 0")\nelse:\n    nums = list(map(int, input().split()))\n    res = [0] * 3\n    for n in nums: res[n] += 1\n    out = [0]*res[0] + [1]*res[1] + [2]*res[2]\n    print(" ".join(map(str, out)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['7', 'ADD 1', 'ADD 2', 'MEDIAN', 'ADD 3', 'MEDIAN', 'ADD 4', 'MEDIAN'], output: ['1.5', '2.0', '2.5'] },
            { input: ['3', 'ADD 5', 'ADD 3', 'MEDIAN'], output: ['4.0'] },
            { input: ['2', 'ADD 1', 'MEDIAN'], output: ['1.0'] },
            { input: ['4', 'ADD 1', 'ADD 1', 'ADD 1', 'MEDIAN'], output: ['1.0'] },
            { input: ['6', 'ADD 10', 'ADD 20', 'ADD 30', 'MEDIAN', 'ADD 40', 'MEDIAN'], output: ['20.0', '25.0'] },
            { input: ['5', 'ADD -1', 'ADD -2', 'MEDIAN', 'ADD -3', 'MEDIAN'], output: ['-1.5', '-2.0'] },
            { input: ['10', 'ADD 1', 'ADD 2', 'ADD 3', 'ADD 4', 'ADD 5', 'ADD 6', 'ADD 7', 'ADD 8', 'ADD 9', 'MEDIAN'], output: ['5.0'] },
            { input: ['4', 'ADD 100', 'ADD 200', 'MEDIAN', 'MEDIAN'], output: ['150.0', '150.0'] },
            { input: ['6', 'ADD 5', 'ADD 10', 'MEDIAN', 'ADD 2', 'ADD 8', 'MEDIAN'], output: ['7.5', '6.5'] },
            { input: ['5', 'ADD 1', 'ADD 3', 'ADD 2', 'MEDIAN', 'MEDIAN'], output: ['2.0', '2.0'] },
            { input: ['7', 'ADD 0', 'ADD 0', 'MEDIAN', 'ADD 0', 'MEDIAN', 'ADD 1', 'MEDIAN'], output: ['0.0', '0.0', '0.0'] },
            { input: ['4', 'ADD 1', 'ADD 10', 'ADD 5', 'MEDIAN'], output: ['5.0'] },
            { input: ['6', 'ADD 1', 'ADD 2', 'ADD 3', 'MEDIAN', 'ADD 4', 'MEDIAN'], output: ['2.0', '2.5'] },
            { input: ['3', 'ADD -10', 'ADD 10', 'MEDIAN'], output: ['0.0'] },
            { input: ['5', 'ADD 100', 'ADD 0', 'ADD -100', 'MEDIAN', 'ADD 50', 'MEDIAN'], output: ['0.0', '25.0'] }
        ],
        videoId: 'itmhHWaHupI'
    };

export const p42 = {
        id: 'p42',
        title: 'Group Anagrams',
        problemStatement: 'Given an array of strings, group the anagrams together. You can return the answer in any order.\n\nAn anagram is a word formed by rearranging the letters of another word using all original letters exactly once.\n\nPrint each group on a separate line, words sorted alphabetically within the group, groups sorted by their first word.',
        inputFormat: 'First line: n. Second line: n space-separated strings.',
        outputFormat: 'Print each anagram group on a separate line, sorted.',
        sampleInput: '6\neat tea tan ate nat bat',
        sampleOutput: 'ate eat tea\nbat\nnat tan',
        difficulty: 'Medium',
        category: 'Hash Table',
        constraints: '1 <= n <= 10^4\n0 <= strs[i].length <= 100\nstrs[i] consists of lowercase English letters.',
        companies: ['Amazon', 'Meta', 'Google', 'Bloomberg'],
        order: 42,
        starterCodes: { python3: '// Group strings that are anagrams of each other\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nres, l, r = [], 0, len(nums) - 1\nwhile l <= r:\n    if abs(nums[l]) > abs(nums[r]):\n        res.append(nums[l]**2); l += 1\n    else:\n        res.append(nums[r]**2); r -= 1\nprint(" ".join(map(str, res[::-1])))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6', 'eat tea tan ate nat bat'], output: ['ate eat tea', 'bat', 'nat tan'] },
            { input: ['1', ''], output: [''] },
            { input: ['1', 'a'], output: ['a'] },
            { input: ['3', 'a b c'], output: ['a', 'b', 'c'] },
            { input: ['4', 'abc bca cab xyz'], output: ['abc bca cab', 'xyz'] },
            { input: ['2', 'aa bb'], output: ['aa', 'bb'] },
            { input: ['3', 'listen silent enlist'], output: ['enlist listen silent'] },
            { input: ['5', 'rat tar art star tsar'], output: ['art rat tar', 'star tsar'] },
            { input: ['4', 'cat dog tac god'], output: ['cat tac', 'dog god'] },
            { input: ['6', 'abc def ghi cba fed ihg'], output: ['abc cba', 'def fed', 'ghi ihg'] },
            { input: ['2', 'ab ba'], output: ['ab ba'] },
            { input: ['3', 'aaa aaa aaa'], output: ['aaa aaa aaa'] },
            { input: ['5', 'a p p l e'], output: ['a', 'e', 'l', 'p p'] },
            { input: ['4', 'test sett stet tset'], output: ['sett stet test tset'] },
            { input: ['3', 'word drow rowd'], output: ['drow rowd word'] }
        ],
        videoId: 'vzdNOK2oB2E'
    };

export const p43 = {
        id: 'p43',
        title: 'Container With Most Water',
        problemStatement: 'You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\n\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\n\nReturn the maximum amount of water a container can store.',
        inputFormat: 'First line: n. Second line: n space-separated integers.',
        outputFormat: 'Print the maximum area.',
        sampleInput: '9\n1 8 6 2 5 4 8 3 7',
        sampleOutput: '49',
        difficulty: 'Medium',
        category: 'Two Pointers',
        constraints: 'n == height.length\n2 <= n <= 10^5\n0 <= height[i] <= 10^4',
        companies: ['Amazon', 'Google', 'Meta', 'Goldman Sachs'],
        order: 43,
        starterCodes: { python3: '// Find the container with the most water using two pointers\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'rows = int(input())\ngrid = [list(map(int, input().split())) for _ in range(rows)]\nif not grid: print(0)\nelse:\n    m, n = len(grid), len(grid[0])\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if grid[i-1][j-1] == 1: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n    print(max(max(row) for row in dp)**2)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['9', '1 8 6 2 5 4 8 3 7'], output: ['49'] },
            { input: ['2', '1 1'], output: ['1'] },
            { input: ['2', '1 2'], output: ['1'] },
            { input: ['5', '4 3 2 1 4'], output: ['16'] },
            { input: ['4', '1 2 4 3'], output: ['4'] },
            { input: ['10', '1 1 1 1 1 1 1 1 1 1'], output: ['9'] },
            { input: ['5', '1 2 3 4 5'], output: ['6'] },
            { input: ['6', '5 4 3 2 1 5'], output: ['25'] },
            { input: ['3', '10 1 10'], output: ['20'] },
            { input: ['4', '1 100 100 1'], output: ['100'] },
            { input: ['2', '10 5'], output: ['5'] },
            { input: ['5', '1 5 1 5 1'], output: ['10'] },
            { input: ['7', '1 2 1 2 1 2 1'], output: ['10'] },
            { input: ['3', '1 1 1'], output: ['2'] },
            { input: ['8', '1 8 1 1 1 1 1 8'], output: ['56'] }
        ],
        videoId: 'UuiTKBwPgAo'
    };

export const p44 = {
        id: 'p44',
        title: 'Edit Distance',
        problemStatement: 'Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted:\n- Insert a character\n- Delete a character\n- Replace a character',
        inputFormat: 'First line: word1. Second line: word2.',
        outputFormat: 'Print the minimum number of operations.',
        sampleInput: 'horse\nros',
        sampleOutput: '3',
        difficulty: 'Hard',
        category: 'Dynamic Programming',
        constraints: '0 <= word1.length, word2.length <= 500\nword1 and word2 consist of lowercase English letters.',
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
        order: 44,
        starterCodes: { python3: '// Compute the edit distance between two strings\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nif not nums: print(0)\nelse:\n    nums.sort()\n    longest = 0\n    nums_set = set(nums)\n    for n in nums:\n        if (n - 1) not in nums_set:\n            length = 0\n            while (n + length) in nums_set: length += 1\n            longest = max(longest, length)\n    print(longest)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['horse', 'ros'], output: ['3'] },
            { input: ['intention', 'execution'], output: ['5'] },
            { input: ['', 'abc'], output: ['3'] },
            { input: ['abc', ''], output: ['3'] },
            { input: ['abc', 'abc'], output: ['0'] },
            { input: ['a', 'b'], output: ['1'] },
            { input: ['ab', 'ac'], output: ['1'] },
            { input: ['ab', 'ba'], output: ['2'] },
            { input: ['abc', 'yabd'], output: ['2'] },
            { input: ['kitten', 'sitting'], output: ['3'] },
            { input: ['flaw', 'lawn'], output: ['2'] },
            { input: ['abc', 'def'], output: ['3'] },
            { input: ['algorithm', 'altruistic'], output: ['6'] },
            { input: ['hello', 'hallo'], output: ['1'] },
            { input: ['sunday', 'monday'], output: ['1'] }
        ],
        videoId: 'XYi2-LPrwm4'
    };

export const p45 = {
        id: 'p45',
        title: 'Three Sum',
        problemStatement: 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.\n\nThe solution set must not contain duplicate triplets. Print each triplet sorted, one per line, triplets in lexicographic order.',
        inputFormat: 'First line: n. Second line: n space-separated integers.',
        outputFormat: 'Print each triplet on a separate line, space-separated.',
        sampleInput: '6\n-1 0 1 2 -1 -4',
        sampleOutput: '-1 -1 2\n-1 0 1',
        difficulty: 'Medium',
        category: 'Two Pointers',
        constraints: '3 <= n <= 3000\n-10^5 <= nums[i] <= 10^5',
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
        order: 45,
        starterCodes: { python3: '// Find all unique triplets that sum to zero\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nif not nums: print(0)\nelse:\n    nums.sort()\n    res = 0\n    for i in range(len(nums) - 2):\n        l, r = i + 1, len(nums) - 1\n        while l < r:\n            if nums[i] + nums[l] > nums[r]:\n                res += r - l\n                r -= 1\n            else: l += 1\n    print(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6', '-1 0 1 2 -1 -4'], output: ['-1 -1 2', '-1 0 1'] },
            { input: ['3', '0 1 1'], output: [] },
            { input: ['3', '0 0 0'], output: ['0 0 0'] },
            { input: ['4', '0 0 0 0'], output: ['0 0 0'] },
            { input: ['5', '-2 0 0 2 2'], output: ['-2 0 2'] },
            { input: ['6', '-2 -1 0 1 2 3'], output: ['-2 -1 3', '-2 0 2', '-1 0 1'] },
            { input: ['4', '1 2 3 4'], output: [] },
            { input: ['5', '-5 1 2 3 4'], output: ['-5 1 4', '-5 2 3'] },
            { input: ['3', '1 -1 0'], output: ['-1 0 1'] },
            { input: ['4', '-1 -1 2 0'], output: ['-1 -1 2'] },
            { input: ['7', '-1 0 1 2 -1 -4 0'], output: ['-1 -1 2', '-1 0 1', '0 0 0'] },
            { input: ['6', '0 0 0 1 1 1'], output: ['0 0 0'] },
            { input: ['5', '-1 -1 -1 2 2'], output: ['-1 -1 2'] },
            { input: ['3', '1 2 3'], output: [] },
            { input: ['6', '-4 -1 -1 0 1 2'], output: ['-1 -1 2', '-1 0 1'] }
        ],
        videoId: 'jzZsG8n2R9A'
    };

export const p46 = {
        id: 'p46',
        title: 'Permutations',
        problemStatement: 'Given an array nums of n distinct integers, return all the possible permutations. You can return the answer in any order.\n\nPrint each permutation on a separate line, space-separated. Sort the permutations lexicographically in your output.',
        inputFormat: 'First line: n. Second line: n space-separated distinct integers.',
        outputFormat: 'Print each permutation on a separate line, elements space-separated.',
        sampleInput: '3\n1 2 3',
        sampleOutput: '1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1',
        difficulty: 'Medium',
        category: 'Backtracking',
        constraints: '1 <= n <= 6\n-10 <= nums[i] <= 10\nAll the integers of nums are unique.',
        companies: ['Google', 'Meta', 'Amazon', 'Microsoft'],
        order: 46,
        starterCodes: { python3: '// Generate all permutations of distinct integers\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nif not nums: print(0)\nelse:\n    res = [1] * len(nums)\n    for i in range(len(nums) - 1, -1, -1):\n        for j in range(i + 1, len(nums)):\n            if nums[i] < nums[j]: res[i] = max(res[i], 1 + res[j])\n    print(max(res))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3', '1 2 3'], output: ['1 2 3', '1 3 2', '2 1 3', '2 3 1', '3 1 2', '3 2 1'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['2', '0 1'], output: ['0 1', '1 0'] },
            { input: ['2', '10 20'], output: ['10 20', '20 10'] },
            { input: ['3', '0 1 2'], output: ['0 1 2', '0 2 1', '1 0 2', '1 2 0', '2 0 1', '2 1 0'] },
            { input: ['1', '0'], output: ['0'] },
            { input: ['2', '-1 1'], output: ['-1 1', '1 -1'] },
            { input: ['3', '3 2 1'], output: ['1 2 3', '1 3 2', '2 1 3', '2 3 1', '3 1 2', '3 2 1'] },
            { input: ['3', '5 6 7'], output: ['5 6 7', '5 7 6', '6 5 7', '6 7 5', '7 5 6', '7 6 5'] },
            { input: ['2', '5 4'], output: ['4 5', '5 4'] },
            { input: ['1', '-5'], output: ['-5'] },
            { input: ['2', '1 2'], output: ['1 2', '2 1'] },
            { input: ['3', '1 3 2'], output: ['1 2 3', '1 3 2', '2 1 3', '2 3 1', '3 1 2', '3 2 1'] },
            { input: ['2', '2 1'], output: ['1 2', '2 1'] },
            { input: ['3', '10 5 0'], output: ['0 5 10', '0 10 5', '5 0 10', '5 10 0', '10 0 5', '10 5 0'] }
        ],
        videoId: 's7AvT7cGdSo'
    };

export const p47 = {
        id: 'p47',
        title: 'Jump Game',
        problemStatement: 'You are given an integer array nums. You are initially positioned at the array\'s first index, and each element in the array represents your maximum jump length at that position.\n\nReturn true if you can reach the last index, or false otherwise.',
        inputFormat: 'First line: n. Second line: n space-separated integers.',
        outputFormat: 'Print "true" if the last index is reachable, "false" otherwise.',
        sampleInput: '5\n2 3 1 1 4',
        sampleOutput: 'true',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= n <= 10^4\n0 <= nums[i] <= 10^5',
        companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
        order: 47,
        starterCodes: { python3: '// Determine if you can reach the last index\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nif not nums: print(0)\nelse:\n    res = nums[0]\n    cur_max, cur_min = 1, 1\n    for n in nums:\n        tmp = cur_max * n\n        cur_max = max(n * cur_max, n * cur_min, n)\n        cur_min = min(tmp, n * cur_min, n)\n        res = max(res, cur_max)\n    print(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['5', '2 3 1 1 4'], output: ['true'] },
            { input: ['5', '3 2 1 0 4'], output: ['false'] },
            { input: ['1', '0'], output: ['true'] },
            { input: ['2', '1 0'], output: ['true'] },
            { input: ['2', '0 1'], output: ['false'] },
            { input: ['3', '1 2 0'], output: ['true'] },
            { input: ['4', '1 1 1 1'], output: ['true'] },
            { input: ['5', '0 1 2 3 4'], output: ['false'] },
            { input: ['6', '2 0 0 0 0 0'], output: ['false'] },
            { input: ['3', '2 1 0'], output: ['true'] },
            { input: ['5', '1 1 1 0 1'], output: ['false'] },
            { input: ['4', '1 0 1 0'], output: ['false'] },
            { input: ['5', '4 0 0 0 1'], output: ['true'] },
            { input: ['3', '1 0 0'], output: ['false'] },
            { input: ['6', '1 2 3 4 5 6'], output: ['true'] }
        ],
        videoId: 'Zb4eRju_lS0'
    };

export const p48 = {
        id: 'p48',
        title: 'Rotate Image',
        problemStatement: 'You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).\n\nYou have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.',
        inputFormat: 'First line: n. Next n lines: n space-separated integers representing the matrix rows.',
        outputFormat: 'Print the rotated matrix, each row on a new line, elements space-separated.',
        sampleInput: '3\n1 2 3\n4 5 6\n7 8 9',
        sampleOutput: '7 4 1\n8 5 2\n9 6 3',
        difficulty: 'Medium',
        category: 'Matrix',
        constraints: 'n == matrix.length == matrix[i].length\n1 <= n <= 20\n-1000 <= matrix[i][j] <= 1000',
        companies: ['Google', 'Amazon', 'Meta', 'Microsoft', 'Apple'],
        order: 48,
        starterCodes: { python3: '// Rotate the n x n matrix 90 degrees clockwise in-place\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nmatrix = [list(map(int, input().split())) for _ in range(n)]\nres = [[0]*n for _ in range(n)]\nfor r in range(n):\n    for c in range(n): res[c][n - 1 - r] = matrix[r][c]\nfor row in res: print(" ".join(map(str, row)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3', '1 2 3', '4 5 6', '7 8 9'], output: ['7 4 1', '8 5 2', '9 6 3'] },
            { input: ['4', '5 1 9 11', '2 4 8 10', '13 3 6 7', '15 14 12 16'], output: ['15 13 2 5', '14 3 4 1', '12 6 8 9', '16 7 10 11'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['2', '1 2', '3 4'], output: ['3 1', '4 2'] },
            { input: ['3', '1 1 1', '2 2 2', '3 3 3'], output: ['3 2 1', '3 2 1', '3 2 1'] },
            { input: ['2', '1 1', '1 1'], output: ['1 1', '1 1'] },
            { input: ['3', '1 2 3', '1 2 3', '1 2 3'], output: ['1 1 1', '2 2 2', '3 3 3'] },
            { input: ['4', '1 2 3 4', '5 6 7 8', '9 10 11 12', '13 14 15 16'], output: ['13 9 5 1', '14 10 6 2', '15 11 7 3', '16 12 8 4'] },
            { input: ['2', '0 0', '0 0'], output: ['0 0', '0 0'] },
            { input: ['3', '-1 -2 -3', '-4 -5 -6', '-7 -8 -9'], output: ['-7 -4 -1', '-8 -5 -2', '-9 -6 -3'] },
            { input: ['2', '10 20', '30 40'], output: ['30 10', '40 20'] },
            { input: ['1', '100'], output: ['100'] },
            { input: ['3', '1 0 0', '0 1 0', '0 0 1'], output: ['0 0 1', '0 1 0', '1 0 0'] },
            { input: ['2', '1 2', '3 4'], output: ['3 1', '4 2'] },
            { input: ['4', '1 1 2 2', '1 1 2 2', '3 3 4 4', '3 3 4 4'], output: ['3 3 1 1', '3 3 1 1', '4 4 2 2', '4 4 2 2'] }
        ],
        videoId: 'gCciKhaK2v8'
    };

export const p49 = {
        id: 'p49',
        title: 'Spiral Matrix II',
        problemStatement: 'Given a positive integer n, generate an n x n matrix filled with elements from 1 to n^2 in spiral order.',
        inputFormat: 'A single integer n.',
        outputFormat: 'Print the n x n matrix, each row on a new line, elements space-separated.',
        sampleInput: '3',
        sampleOutput: '1 2 3\n8 9 4\n7 6 5',
        difficulty: 'Medium',
        category: 'Matrix',
        constraints: '1 <= n <= 20',
        companies: ['Amazon', 'Microsoft', 'Apple', 'Google'],
        order: 49,
        starterCodes: { python3: '// Generate an n x n spiral matrix\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nres = [[0] * n for _ in range(n)]\nl, r = 0, n\nt, b = 0, n\nval = 1\nwhile l < r and t < b:\n    for i in range(l, r): res[t][i] = val; val += 1\n    t += 1\n    for i in range(t, b): res[i][r - 1] = val; val += 1\n    r -= 1\n    if not (l < r and t < b): break\n    for i in range(r - 1, l - 1, -1): res[b - 1][i] = val; val += 1\n    b -= 1\n    for i in range(b - 1, t - 1, -1): res[i][l] = val; val += 1\n    l += 1\nfor row in res: print(" ".join(map(str, row)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['1'], output: ['1'] },
            { input: ['2'], output: ['1 2', '4 3'] },
            { input: ['3'], output: ['1 2 3', '8 9 4', '7 6 5'] },
            { input: ['4'], output: ['1 2 3 4', '12 13 14 5', '11 16 15 6', '10 9 8 7'] },
            { input: ['5'], output: ['1 2 3 4 5', '16 17 18 19 6', '15 24 25 20 7', '14 23 22 21 8', '13 12 11 10 9'] },
            { input: ['1'], output: ['1'] },
            { input: ['2'], output: ['1 2', '4 3'] },
            { input: ['3'], output: ['1 2 3', '8 9 4', '7 6 5'] },
            { input: ['4'], output: ['1 2 3 4', '12 13 14 5', '11 16 15 6', '10 9 8 7'] },
            { input: ['2'], output: ['1 2', '4 3'] },
            { input: ['1'], output: ['1'] },
            { input: ['3'], output: ['1 2 3', '8 9 4', '7 6 5'] },
            { input: ['5'], output: ['1 2 3 4 5', '16 17 18 19 6', '15 24 25 20 7', '14 23 22 21 8', '13 12 11 10 9'] },
            { input: ['4'], output: ['1 2 3 4', '12 13 14 5', '11 16 15 6', '10 9 8 7'] },
            { input: ['2'], output: ['1 2', '4 3'] }
        ],
        videoId: 'WLSKz6yzSBo'
    };

export const p50 = {
        id: 'p50',
        title: 'Pow(x, n)',
        problemStatement: 'Implement pow(x, n), which calculates x raised to the power n (i.e., x^n).',
        inputFormat: 'First line: a double x and an integer n.',
        outputFormat: 'Print the result x^n, formatted to 5 decimal places.',
        sampleInput: '2.00000 10',
        sampleOutput: '1024.00000',
        difficulty: 'Medium',
        category: 'Math',
        constraints: '-100.0 < x < 100.0\n-2^31 <= n <= 2^31-1\nn is an integer.\n-10^4 <= x^n <= 10^4',
        companies: ['Meta', 'Google', 'Amazon', 'Microsoft'],
        order: 50,
        starterCodes: { python3: '// Compute x raised to the power n\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'import sys\nline = sys.stdin.readline()\nif not line: sys.exit(0)\nx, n = map(float, line.split())\nn = int(n)\ndef power(x, n):\n    if x == 0: return 0\n    if n == 0: return 1\n    res = power(x, abs(n) // 2)\n    res = res * res\n    if n % 2: res = x * res\n    return res if n >= 0 else 1 / res\nprint(f"{power(x, n):.5f}")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['2.00000 10'], output: ['1024.00000'] },
            { input: ['2.10000 3'], output: ['9.26100'] },
            { input: ['2.00000 -2'], output: ['0.25000'] },
            { input: ['1.00000 2147483647'], output: ['1.00000'] },
            { input: ['-1.00000 2147483647'], output: ['-1.00000'] },
            { input: ['2.00000 0'], output: ['1.00000'] },
            { input: ['0.00000 5'], output: ['0.00000'] },
            { input: ['1.10000 2'], output: ['1.21000'] },
            { input: ['-2.00000 2'], output: ['4.00000'] },
            { input: ['-2.00000 3'], output: ['-8.00000'] },
            { input: ['0.50000 2'], output: ['0.25000'] },
            { input: ['2.00000 -3'], output: ['0.12500'] },
            { input: ['1.00001 0'], output: ['1.00000'] },
            { input: ['-1.00000 2'], output: ['1.00000'] },
            { input: ['0.00001 1'], output: ['0.00001'] }
        ],
        videoId: 'g9YQyYi4IQQ'
    };

