// Batch 1 of problems

export const p1 = {
        id: 'p1',
        title: 'Two Sum',
        problemStatement: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.',
        inputFormat: 'First line contains n (size of array) and target separated by space. Second line contains n space-separated integers.',
        outputFormat: 'Print the two indices separated by a space.',
        sampleInput: '4 9\n2 7 11 15',
        sampleOutput: '0 1',
        difficulty: 'Easy',
        category: 'Arrays',
        constraints: '2 <= n <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9',
        companies: ['Google', 'Amazon', 'Meta', 'Apple'],
        order: 1,
        starterCodes: { python3: '// Read input and find two indices whose values sum to target\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n, target = map(int, input().split())\nnums = list(map(int, input().split()))\n\ndef solve():\n    prevMap = {}\n    for i, n in enumerate(nums):\n        diff = target - n\n        if diff in prevMap:\n            return [prevMap[diff], i]\n        prevMap[n] = i\n\nres = solve()\nprint(f"{res[0]} {res[1]}")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['4 9', '2 7 11 15'], output: ['0 1'] },
            { input: ['3 6', '3 2 4'], output: ['1 2'] },
            { input: ['2 6', '3 3'], output: ['0 1'] },
            { input: ['2 -2', '-3 1'], output: ['0 1'] },
            { input: ['2 0', '5 -5'], output: ['0 1'] },
            { input: ['2 2000000000', '1000000000 1000000000'], output: ['0 1'] },
            { input: ['4 8', '4 4 4 4'], output: ['0 1'] },
            { input: ['5 10', '1 2 3 4 9'], output: ['0 4'] },
            { input: ['4 5', '1 2 3 6'], output: ['1 2'] },
            { input: ['3 0', '-1 2 1'], output: ['0 2'] },
            { input: ['10 100', '1 2 3 4 5 6 7 8 9 91'], output: ['8 9'] },
            { input: ['3 6', '2 4 3'], output: ['0 1'] },
            { input: ['2 5', '2 3'], output: ['0 1'] },
            { input: ['4 7', '3 1 2 4'], output: ['0 3'] },
            { input: ['2 1000000', '500000 500000'], output: ['0 1'] }
        ],
        videoId: 'dQw4w9WgXcQ'
    };

export const p2 = {
        id: 'p2',
        title: 'Reverse Linked List',
        problemStatement: 'Given the head of a singly linked list, reverse the list, and return the reversed list.\n\nYou are given the list as space-separated values. Reverse all nodes and print the result.',
        inputFormat: 'First line contains n (number of nodes). Second line contains n space-separated integers representing node values.',
        outputFormat: 'Print the reversed list as space-separated values.',
        sampleInput: '5\n1 2 3 4 5',
        sampleOutput: '5 4 3 2 1',
        difficulty: 'Medium',
        category: 'Linked List',
        constraints: '0 <= n <= 5000\n-5000 <= Node.val <= 5000',
        companies: ['Microsoft', 'Amazon', 'Bloomberg'],
        order: 2,
        starterCodes: { python3: '// Read the linked list and reverse it\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n == 0:\n    print("")\nelse:\n    nodes = input().split()\n    print(" ".join(nodes[::-1]))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['5', '1 2 3 4 5'], output: ['5 4 3 2 1'] },
            { input: ['3', '1 2 3'], output: ['3 2 1'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['0', ''], output: [''] },
            { input: ['2', '1 2'], output: ['2 1'] },
            { input: ['4', '1 1 1 1'], output: ['1 1 1 1'] },
            { input: ['3', '-1 -2 -3'], output: ['-3 -2 -1'] },
            { input: ['4', '1 2 1 2'], output: ['2 1 2 1'] },
            { input: ['1', '100000'], output: ['100000'] },
            { input: ['5', '10 20 30 40 50'], output: ['50 40 30 20 10'] },
            { input: ['3', '1 2 1'], output: ['1 2 1'] },
            { input: ['10', '1 2 3 4 5 6 7 8 9 10'], output: ['10 9 8 7 6 5 4 3 2 1'] },
            { input: ['3', '3 2 1'], output: ['1 2 3'] },
            { input: ['1', '-5000'], output: ['-5000'] },
            { input: ['2', '0 0'], output: ['0 0'] }
        ],
        videoId: '8-k1C6ehKuw'
    };

export const p3 = {
        id: 'p3',
        title: 'Dijkstra Shortest Path',
        problemStatement: 'Given a weighted directed graph with V vertices (0 to V-1) and E edges, find the shortest distance from a source vertex S to all other vertices.\n\nIf a vertex is unreachable from S, print -1 for that vertex.',
        inputFormat: 'First line: V E S (vertices, edges, source). Next E lines each contain: u v w (edge from u to v with weight w).',
        outputFormat: 'Print V space-separated shortest distances from source to each vertex (0 to V-1).',
        sampleInput: '5 6 0\n0 1 2\n0 2 4\n1 2 1\n1 3 7\n2 4 3\n3 4 1',
        sampleOutput: '0 2 3 9 6',
        difficulty: 'Hard',
        category: 'Graphs',
        constraints: '1 <= V <= 1000\n1 <= E <= V*(V-1)\n0 <= w <= 10^4',
        companies: ['Google', 'Uber', 'Apple'],
        order: 3,
        starterCodes: { python3: '// Implement Dijkstra\'s shortest path algorithm\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'import heapq\nv, e, s = map(int, input().split())\nadj = [[] for _ in range(v)]\nfor _ in range(e):\n    u, v_dest, w = map(int, input().split())\n    adj[u].append((v_dest, w))\n\ndist = [-1] * v\ndist[s] = 0\npq = [(0, s)]\n\nwhile pq:\n    d, u = heapq.heappop(pq)\n    if d > dist[u] and dist[u] != -1: continue\n    for v_dest, w in adj[u]:\n        if dist[v_dest] == -1 or dist[u] + w < dist[v_dest]:\n            dist[v_dest] = dist[u] + w\n            heapq.heappush(pq, (dist[v_dest], v_dest))\n\nprint(" ".join(map(str, dist)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['5 6 0', '0 1 2', '0 2 4', '1 2 1', '1 3 7', '2 4 3', '3 4 1'], output: ['0 2 3 9 6'] },
            { input: ['3 3 0', '0 1 1', '1 2 2', '0 2 4'], output: ['0 1 3'] },
            { input: ['3 1 0', '0 1 5'], output: ['0 5 -1'] },
            { input: ['1 0 0'], output: ['0'] },
            { input: ['2 1 0', '0 1 10'], output: ['0 10'] },
            { input: ['3 3 0', '0 1 2', '1 2 3', '2 0 1'], output: ['0 2 5'] },
            { input: ['3 2 0', '0 1 0', '1 2 0'], output: ['0 0 0'] },
            { input: ['4 3 0', '0 1 1', '1 2 1', '2 3 1'], output: ['0 1 2 3'] },
            { input: ['3 2 0', '0 1 10', '0 2 5', '2 1 2'], output: ['0 7 5'] },
            { input: ['3 0 0'], output: ['0 -1 -1'] },
            { input: ['3 2 2', '0 1 1', '1 2 1'], output: ['-1 -1 0'] },
            { input: ['2 2 0', '0 1 5', '1 0 5'], output: ['0 5'] },
            { input: ['2 2 0', '0 1 10', '0 1 5'], output: ['0 5'] },
            { input: ['5 4 0', '0 1 1', '1 2 1', '2 3 1', '3 4 1'], output: ['0 1 2 3 4'] },
            { input: ['2 1 0', '0 1 10000'], output: ['0 10000'] }
        ],
        videoId: 'h2f1YQz3G6g'
    };

export const p4 = {
        id: 'p4',
        title: 'Valid Parentheses',
        problemStatement: 'Given a string s containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.',
        inputFormat: 'A single line containing the string s.',
        outputFormat: 'Print "true" if valid, "false" otherwise.',
        sampleInput: '()[]{}',
        sampleOutput: 'true',
        difficulty: 'Easy',
        category: 'Stacks',
        constraints: '1 <= s.length <= 10^4\ns consists of parentheses only \'()[]{}\'',
        companies: ['Amazon', 'Meta', 'Bloomberg'],
        order: 4,
        starterCodes: { python3: '// Check if the parentheses string is valid\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 's = input().strip()\ndef isValid(s):\n    stack = []\n    closeToOpen = {")": "(", "]": "[", "}": "{"}\n    for c in s:\n        if c in closeToOpen:\n            if stack and stack[-1] == closeToOpen[c]:\n                stack.pop()\n            else:\n                return False\n        else:\n            stack.append(c)\n    return True if not stack else False\nprint("true" if isValid(s) else "false")', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['()[]{}'], output: ['true'] },
            { input: ['(]'], output: ['false'] },
            { input: ['{[]}'], output: ['true'] },
            { input: ['([)]'], output: ['false'] },
            { input: ['()'], output: ['true'] },
            { input: ['['], output: ['false'] },
            { input: [']'], output: ['false'] },
            { input: ['((()))'], output: ['true'] },
            { input: ['(([]){})'], output: ['true'] },
            { input: [')('], output: ['false'] },
            { input: ['(('], output: ['false'] },
            { input: ['))'], output: ['false'] },
            { input: ['{()}'], output: ['true'] },
            { input: ['({[]})'], output: ['true'] },
            { input: ['((((((()))))))'], output: ['true'] }
        ],
        videoId: 'WTzjTskDFMg'
    };

export const p5 = {
        id: 'p5',
        title: 'Maximum Subarray',
        problemStatement: 'Given an integer array nums, find the subarray with the largest sum, and return its sum.\n\nA subarray is a contiguous non-empty sequence of elements within an array.',
        inputFormat: 'First line contains n (size of array). Second line contains n space-separated integers.',
        outputFormat: 'Print the maximum subarray sum.',
        sampleInput: '9\n-2 1 -3 4 -1 2 1 -5 4',
        sampleOutput: '6',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= n <= 10^5\n-10^4 <= nums[i] <= 10^4',
        companies: ['Amazon', 'Apple', 'Microsoft', 'LinkedIn'],
        order: 5,
        starterCodes: { python3: '// Find the maximum subarray sum using Kadane\'s algorithm\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nnums = list(map(int, input().split()))\nmax_sub = nums[0]\ncur_sum = 0\nfor n in nums:\n    if cur_sum < 0: cur_sum = 0\n    cur_sum += n\n    max_sub = max(max_sub, cur_sum)\nprint(max_sub)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['9', '-2 1 -3 4 -1 2 1 -5 4'], output: ['6'] },
            { input: ['1', '1'], output: ['1'] },
            { input: ['5', '5 4 -1 7 8'], output: ['23'] },
            { input: ['3', '-1 -2 -3'], output: ['-1'] },
            { input: ['3', '1 2 3'], output: ['6'] },
            { input: ['2', '-2 1'], output: ['1'] },
            { input: ['2', '1 -2'], output: ['1'] },
            { input: ['5', '-2 -1 -3 -4 -1'], output: ['-1'] },
            { input: ['4', '1 2 -1 4'], output: ['6'] },
            { input: ['4', '4 -1 2 1'], output: ['6'] },
            { input: ['3', '5 -2 5'], output: ['10'] },
            { input: ['4', '-1 2 3 -2'], output: ['5'] },
            { input: ['5', '1 -1 1 -1 1'], output: ['1'] },
            { input: ['6', '-2 1 -3 4 -1 2'], output: ['5'] },
            { input: ['2', '0 0'], output: ['0'] }
        ],
        videoId: '5WZl3MMT0Eg'
    };

export const p6 = {
        id: 'p6',
        title: 'Binary Search',
        problemStatement: 'Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return -1.\n\nYou must write an algorithm with O(log n) runtime complexity.',
        inputFormat: 'First line contains n and target. Second line contains n sorted space-separated integers.',
        outputFormat: 'Print the index of target, or -1 if not found.',
        sampleInput: '6 9\n-1 0 3 5 9 12',
        sampleOutput: '4',
        difficulty: 'Easy',
        category: 'Binary Search',
        constraints: '1 <= n <= 10^4\n-10^4 < nums[i], target < 10^4\nAll integers in nums are unique.\nnums is sorted in ascending order.',
        companies: ['Google', 'Microsoft', 'Apple'],
        order: 6,
        starterCodes: { python3: '// Implement binary search on a sorted array\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n, target = map(int, input().split())\nnums = list(map(int, input().split()))\nl, r = 0, n - 1\nres = -1\nwhile l <= r:\n    m = (l + r) // 2\n    if nums[m] == target:\n        res = m\n        break\n    elif nums[m] < target: l = m + 1\n    else: r = m - 1\nprint(res)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6 9', '-1 0 3 5 9 12'], output: ['4'] },
            { input: ['6 2', '-1 0 3 5 9 12'], output: ['-1'] },
            { input: ['1 5', '5'], output: ['0'] },
            { input: ['1 2', '5'], output: ['-1'] },
            { input: ['2 1', '1 2'], output: ['0'] },
            { input: ['2 2', '1 2'], output: ['1'] },
            { input: ['5 3', '1 2 3 4 5'], output: ['2'] },
            { input: ['5 1', '1 2 3 4 5'], output: ['0'] },
            { input: ['5 5', '1 2 3 4 5'], output: ['4'] },
            { input: ['4 10', '1 3 5 7'], output: ['-1'] },
            { input: ['4 0', '1 3 5 7'], output: ['-1'] },
            { input: ['3 2', '1 2 3'], output: ['1'] },
            { input: ['10 7', '1 2 3 4 5 6 7 8 9 10'], output: ['6'] },
            { input: ['5 -1', '-5 -3 -1 0 2'], output: ['2'] },
            { input: ['2 0', '0 1'], output: ['0'] }
        ],
        videoId: 'sSgU2Jo_vpM'
    };

export const p7 = {
        id: 'p7',
        title: 'Merge Two Sorted Lists',
        problemStatement: 'You are given two sorted linked lists (as arrays). Merge the two lists into one sorted list by splicing together the nodes.\n\nReturn the merged sorted list.',
        inputFormat: 'First line: n m (sizes of the two lists). Second line: n sorted integers. Third line: m sorted integers.',
        outputFormat: 'Print the merged sorted list as space-separated values.',
        sampleInput: '3 3\n1 2 4\n1 3 4',
        sampleOutput: '1 1 2 3 4 4',
        difficulty: 'Easy',
        category: 'Linked List',
        constraints: '0 <= n, m <= 50\n-100 <= Node.val <= 100\nBoth lists are sorted in non-decreasing order.',
        companies: ['Amazon', 'Microsoft', 'Apple'],
        order: 7,
        starterCodes: { python3: '// Merge two sorted lists into one sorted list\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n, m = map(int, input().split())\nl1 = list(map(int, input().split())) if n > 0 else []\nl2 = list(map(int, input().split())) if m > 0 else []\nres = sorted(l1 + l2)\nprint(" ".join(map(str, res)))', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['3 3', '1 2 4', '1 3 4'], output: ['1 1 2 3 4 4'] },
            { input: ['0 0', '', ''], output: [''] },
            { input: ['0 1', '', '0'], output: ['0'] },
            { input: ['1 0', '0', ''], output: ['0'] },
            { input: ['1 1', '2', '1'], output: ['1 2'] },
            { input: ['2 2', '1 3', '2 4'], output: ['1 2 3 4'] },
            { input: ['3 1', '1 2 3', '4'], output: ['1 2 3 4'] },
            { input: ['1 3', '0', '1 2 3'], output: ['0 1 2 3'] },
            { input: ['2 2', '1 1', '1 1'], output: ['1 1 1 1'] },
            { input: ['3 3', '-10 0 10', '-5 5 15'], output: ['-10 -5 0 5 10 15'] },
            { input: ['2 1', '5 10', '7'], output: ['5 7 10'] },
            { input: ['1 2', '1', '1 1'], output: ['1 1 1'] },
            { input: ['3 2', '1 2 5', '3 4'], output: ['1 2 3 4 5'] },
            { input: ['2 2', '1 2', '3 4'], output: ['1 2 3 4'] },
            { input: ['2 2', '3 4', '1 2'], output: ['1 2 3 4'] }
        ],
        videoId: 'XIdigk956u0'
    };

export const p8 = {
        id: 'p8',
        title: 'Climbing Stairs',
        problemStatement: 'You are climbing a staircase. It takes n steps to reach the top.\n\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?',
        inputFormat: 'A single integer n.',
        outputFormat: 'Print the number of distinct ways to climb to the top.',
        sampleInput: '5',
        sampleOutput: '8',
        difficulty: 'Easy',
        category: 'Dynamic Programming',
        constraints: '1 <= n <= 45',
        companies: ['Amazon', 'Apple', 'Adobe'],
        order: 8,
        starterCodes: { python3: '// Count the number of ways to climb n stairs\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nif n <= 2: print(n)\nelse:\n    one, two = 1, 2\n    for i in range(3, n + 1):\n        temp = one + two\n        one = two\n        two = temp\n    print(two)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['1'], output: ['1'] },
            { input: ['2'], output: ['2'] },
            { input: ['3'], output: ['3'] },
            { input: ['4'], output: ['5'] },
            { input: ['5'], output: ['8'] },
            { input: ['6'], output: ['13'] },
            { input: ['10'], output: ['89'] },
            { input: ['20'], output: ['10946'] },
            { input: ['30'], output: ['1346269'] },
            { input: ['40'], output: ['165580141'] },
            { input: ['45'], output: ['1836311903'] },
            { input: ['7'], output: ['21'] },
            { input: ['8'], output: ['34'] },
            { input: ['9'], output: ['55'] },
            { input: ['15'], output: ['987'] }
        ],
        videoId: 'Y0lT9Fck7qI'
    };

export const p9 = {
        id: 'p9',
        title: 'Best Time to Buy and Sell Stock',
        problemStatement: 'You are given an array prices where prices[i] is the price of a given stock on the ith day.\n\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\n\nReturn the maximum profit you can achieve. If you cannot achieve any profit, return 0.',
        inputFormat: 'First line contains n. Second line contains n space-separated prices.',
        outputFormat: 'Print the maximum profit.',
        sampleInput: '6\n7 1 5 3 6 4',
        sampleOutput: '5',
        difficulty: 'Easy',
        category: 'Arrays',
        constraints: '1 <= n <= 10^5\n0 <= prices[i] <= 10^4',
        companies: ['Amazon', 'Meta', 'Goldman Sachs', 'Microsoft'],
        order: 9,
        starterCodes: { python3: '// Find the maximum profit from buying and selling stock\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 'n = int(input())\nprices = list(map(int, input().split()))\nl, r = 0, 1\nmax_p = 0\nwhile r < n:\n    if prices[l] < prices[r]:\n        max_p = max(max_p, prices[r] - prices[l])\n    else: l = r\n    r += 1\nprint(max_p)', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['6', '7 1 5 3 6 4'], output: ['5'] },
            { input: ['5', '7 6 4 3 1'], output: ['0'] },
            { input: ['4', '2 4 1 7'], output: ['6'] },
            { input: ['1', '10'], output: ['0'] },
            { input: ['2', '1 5'], output: ['4'] },
            { input: ['2', '5 1'], output: ['0'] },
            { input: ['5', '1 2 3 4 5'], output: ['4'] },
            { input: ['5', '5 4 3 2 1'], output: ['0'] },
            { input: ['6', '1 10 1 10 1 10'], output: ['9'] },
            { input: ['3', '10 1 5'], output: ['4'] },
            { input: ['4', '3 3 3 3'], output: ['0'] },
            { input: ['5', '1 2 1 2 1'], output: ['1'] },
            { input: ['2', '0 10000'], output: ['10000'] },
            { input: ['6', '1 2 4 8 16 32'], output: ['31'] },
            { input: ['5', '10 7 5 8 11'], output: ['6'] }
        ],
        videoId: '1pkOgXD63yU'
    };

export const p10 = {
        id: 'p10',
        title: 'Longest Common Subsequence',
        problemStatement: 'Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.\n\nA subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.',
        inputFormat: 'First line: text1. Second line: text2.',
        outputFormat: 'Print the length of the longest common subsequence.',
        sampleInput: 'abcde\nace',
        sampleOutput: '3',
        difficulty: 'Medium',
        category: 'Dynamic Programming',
        constraints: '1 <= text1.length, text2.length <= 1000\ntext1 and text2 consist of only lowercase English characters.',
        companies: ['Google', 'Amazon', 'Karat'],
        order: 10,
        starterCodes: { python3: '// Find the longest common subsequence of two strings\n', cpp: '', java: '', nodejs: '' }, solutions: { python3: 's1 = input().strip()\ns2 = input().strip()\ndp = [[0 for _ in range(len(s2) + 1)] for _ in range(len(s1) + 1)]\nfor i in range(len(s1) - 1, -1, -1):\n    for j in range(len(s2) - 1, -1, -1):\n        if s1[i] == s2[j]: dp[i][j] = 1 + dp[i+1][j+1]\n        else: dp[i][j] = max(dp[i+1][j], dp[i][j+1])\nprint(dp[0][0])', cpp: '', java: '', nodejs: '' },
        testCases: [
            { input: ['abcde', 'ace'], output: ['3'] },
            { input: ['abc', 'abc'], output: ['3'] },
            { input: ['abc', 'def'], output: ['0'] },
            { input: ['a', 'a'], output: ['1'] },
            { input: ['a', 'b'], output: ['0'] },
            { input: ['abc', 'ac'], output: ['2'] },
            { input: ['bl', 'yby'], output: ['1'] },
            { input: ['aaa', 'aa'], output: ['2'] },
            { input: ['oxcpqrsvwf', 'shmtulqzyw'], output: ['2'] },
            { input: ['abcdef', 'abc'], output: ['3'] },
            { input: ['abc', 'abcdef'], output: ['3'] },
            { input: ['ezupkr', 'ubmrapg'], output: ['2'] },
            { input: ['bsbininm', 'jmjkbkjkv'], output: ['1'] },
            { input: ['longest', 'stone'], output: ['3'] },
            { input: ['algorithm', 'altruistic'], output: ['3'] }
        ],
        videoId: 'Ua0GhsJSlWM'
    };

